/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6 */

#ifndef PB_SUBSTRAIT_SUBSTRAIT_ANY_PB_H_INCLUDED
#define PB_SUBSTRAIT_SUBSTRAIT_ANY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _substrait_Any { 
    char *type_url;
    pb_bytes_array_t *value;
} substrait_Any;

typedef struct _substrait_Empty { 
    char dummy_field;
} substrait_Empty;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define substrait_Any_init_default               {NULL, NULL}
#define substrait_Empty_init_default             {0}
#define substrait_Any_init_zero                  {NULL, NULL}
#define substrait_Empty_init_zero                {0}

/* Field tags (for use in manual encoding/decoding) */
#define substrait_Any_type_url_tag               1
#define substrait_Any_value_tag                  2

/* Struct field encoding specification for nanopb */
#define substrait_Any_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   type_url,          1) \
X(a, POINTER,  SINGULAR, BYTES,    value,             2)
#define substrait_Any_CALLBACK NULL
#define substrait_Any_DEFAULT NULL

#define substrait_Empty_FIELDLIST(X, a) \

#define substrait_Empty_CALLBACK NULL
#define substrait_Empty_DEFAULT NULL

extern const pb_msgdesc_t substrait_Any_msg;
extern const pb_msgdesc_t substrait_Empty_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define substrait_Any_fields &substrait_Any_msg
#define substrait_Empty_fields &substrait_Empty_msg

/* Maximum encoded size of messages (where known) */
/* substrait_Any_size depends on runtime parameters */
#define substrait_Empty_size                     0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
