/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_SUBSTRAIT_SUBSTRAIT_EXPRESSION_PB_H_INCLUDED
#define PB_SUBSTRAIT_SUBSTRAIT_EXPRESSION_PB_H_INCLUDED
#include <pb.h>
#include "substrait/type.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _substrait_AggregationPhase { 
    substrait_AggregationPhase_AGGREGATION_PHASE_UNSPECIFIED = 0, 
    substrait_AggregationPhase_AGGREGATION_PHASE_INITIAL_TO_INTERMEDIATE = 1, 
    substrait_AggregationPhase_AGGREGATION_PHASE_INTERMEDIATE_TO_INTERMEDIATE = 2, 
    substrait_AggregationPhase_AGGREGATION_PHASE_INITIAL_TO_RESULT = 3, 
    substrait_AggregationPhase_AGGREGATION_PHASE_INTERMEDIATE_TO_RESULT = 4 
} substrait_AggregationPhase;

typedef enum _substrait_SortField_SortDirection { 
    substrait_SortField_SortDirection_SORT_DIRECTION_UNSPECIFIED = 0, 
    substrait_SortField_SortDirection_SORT_DIRECTION_ASC_NULLS_FIRST = 1, 
    substrait_SortField_SortDirection_SORT_DIRECTION_ASC_NULLS_LAST = 2, 
    substrait_SortField_SortDirection_SORT_DIRECTION_DESC_NULLS_FIRST = 3, 
    substrait_SortField_SortDirection_SORT_DIRECTION_DESC_NULLS_LAST = 4, 
    substrait_SortField_SortDirection_SORT_DIRECTION_CLUSTERED = 5 
} substrait_SortField_SortDirection;

/* Struct definitions */
typedef struct _substrait_AggregateFunction { 
    uint32_t *function_reference; 
    pb_size_t args_count;
    struct _substrait_Expression *args; 
    pb_size_t sorts_count;
    struct _substrait_SortField *sorts; 
    substrait_AggregationPhase *phase; 
    struct _substrait_Type *output_type; 
} substrait_AggregateFunction;

typedef struct _substrait_Expression { 
    pb_size_t which_rex_type;
    union {
        struct _substrait_Expression_Literal *literal;
        struct _substrait_Expression_FieldReference *selection;
        struct _substrait_Expression_ScalarFunction *scalar_function;
        struct _substrait_Expression_WindowFunction *window_function;
        struct _substrait_Expression_IfThen *if_then;
        struct _substrait_Expression_SwitchExpression *switch_expression;
        struct _substrait_Expression_SingularOrList *singular_or_list;
        struct _substrait_Expression_MultiOrList *multi_or_list;
        struct _substrait_Expression_Enum *enum_;
        struct _substrait_Expression_Cast *cast;
    } rex_type; 
} substrait_Expression;

typedef struct _substrait_Expression_Cast { 
    struct _substrait_Type *type; 
    struct _substrait_Expression *input; 
} substrait_Expression_Cast;

typedef struct _substrait_Expression_EmbeddedFunction { 
    pb_size_t arguments_count;
    struct _substrait_Expression *arguments; 
    struct _substrait_Type *output_type; 
    pb_size_t which_kind;
    union {
        struct _substrait_Expression_EmbeddedFunction_PythonPickleFunction *python_pickle_function;
        struct _substrait_Expression_EmbeddedFunction_WebAssemblyFunction *web_assembly_function;
    } kind; 
} substrait_Expression_EmbeddedFunction;

typedef struct _substrait_Expression_EmbeddedFunction_PythonPickleFunction { 
    pb_bytes_array_t *function; 
    pb_size_t prerequisite_count;
    char **prerequisite; 
} substrait_Expression_EmbeddedFunction_PythonPickleFunction;

typedef struct _substrait_Expression_EmbeddedFunction_WebAssemblyFunction { 
    pb_bytes_array_t *script; 
    pb_size_t prerequisite_count;
    char **prerequisite; 
} substrait_Expression_EmbeddedFunction_WebAssemblyFunction;

typedef struct _substrait_Expression_Enum { 
    pb_size_t which_enum_kind;
    union {
        char *specified;
        struct _substrait_Expression_Enum_Empty *unspecified;
    } enum_kind; 
} substrait_Expression_Enum;

typedef struct _substrait_Expression_Enum_Empty { 
    char dummy_field;
} substrait_Expression_Enum_Empty;

typedef struct _substrait_Expression_FieldReference { 
    pb_size_t which_reference_type;
    union {
        struct _substrait_Expression_ReferenceSegment *direct_reference;
        struct _substrait_Expression_MaskExpression *masked_reference;
    } reference_type; 
    pb_size_t which_root_type;
    union {
        struct _substrait_Expression *expression;
        struct _substrait_Expression_FieldReference_RootReference *root_reference;
    } root_type; 
} substrait_Expression_FieldReference;

typedef struct _substrait_Expression_FieldReference_RootReference { 
    char dummy_field;
} substrait_Expression_FieldReference_RootReference;

typedef struct _substrait_Expression_IfThen { 
    pb_size_t ifs_count;
    struct _substrait_Expression_IfThen_IfClause *ifs; 
    struct _substrait_Expression *else_; 
} substrait_Expression_IfThen;

typedef struct _substrait_Expression_IfThen_IfClause { 
    struct _substrait_Expression *if_; 
    struct _substrait_Expression *then; 
} substrait_Expression_IfThen_IfClause;

typedef struct _substrait_Expression_Literal { 
    pb_size_t which_literal_type;
    union {
        bool *boolean;
        int32_t *i8;
        int32_t *i16;
        int32_t *i32;
        int64_t *i64;
        float *fp32;
        double *fp64;
        char *string;
        pb_bytes_array_t *binary;
        int64_t *timestamp;
        int32_t *date;
        int64_t *time;
        struct _substrait_Expression_Literal_IntervalYearToMonth *interval_year_to_month;
        struct _substrait_Expression_Literal_IntervalDayToSecond *interval_day_to_second;
        char *fixed_char;
        struct _substrait_Expression_Literal_VarChar *var_char;
        pb_bytes_array_t *fixed_binary;
        struct _substrait_Expression_Literal_Decimal *decimal;
        struct _substrait_Expression_Literal_Struct *struct_;
        struct _substrait_Expression_Literal_Map *map;
        int64_t *timestamp_tz;
        pb_bytes_array_t *uuid;
        struct _substrait_Type *null;
        struct _substrait_Expression_Literal_List *list;
        struct _substrait_Type_List *empty_list;
        struct _substrait_Type_Map *empty_map;
    } literal_type; 
    bool *nullable; 
} substrait_Expression_Literal;

typedef struct _substrait_Expression_Literal_Decimal { 
    pb_bytes_array_t *value; 
    int32_t *precision; 
    int32_t *scale; 
} substrait_Expression_Literal_Decimal;

typedef struct _substrait_Expression_Literal_IntervalDayToSecond { 
    int32_t *days; 
    int32_t *seconds; 
} substrait_Expression_Literal_IntervalDayToSecond;

typedef struct _substrait_Expression_Literal_IntervalYearToMonth { 
    int32_t *years; 
    int32_t *months; 
} substrait_Expression_Literal_IntervalYearToMonth;

typedef struct _substrait_Expression_Literal_List { 
    pb_size_t values_count;
    struct _substrait_Expression_Literal *values; 
} substrait_Expression_Literal_List;

typedef struct _substrait_Expression_Literal_Map { 
    pb_size_t key_values_count;
    struct _substrait_Expression_Literal_Map_KeyValue *key_values; 
} substrait_Expression_Literal_Map;

typedef struct _substrait_Expression_Literal_Map_KeyValue { 
    struct _substrait_Expression_Literal *key; 
    struct _substrait_Expression_Literal *value; 
} substrait_Expression_Literal_Map_KeyValue;

typedef struct _substrait_Expression_Literal_Struct { 
    pb_size_t fields_count;
    struct _substrait_Expression_Literal *fields; 
} substrait_Expression_Literal_Struct;

typedef struct _substrait_Expression_Literal_VarChar { 
    char *value; 
    uint32_t *length; 
} substrait_Expression_Literal_VarChar;

typedef struct _substrait_Expression_MaskExpression { 
    struct _substrait_Expression_MaskExpression_StructSelect *select; 
    bool *maintain_singular_struct; 
} substrait_Expression_MaskExpression;

typedef struct _substrait_Expression_MaskExpression_ListSelect { 
    pb_size_t selection_count;
    struct _substrait_Expression_MaskExpression_ListSelect_ListSelectItem *selection; 
    struct _substrait_Expression_MaskExpression_Select *child; 
} substrait_Expression_MaskExpression_ListSelect;

typedef struct _substrait_Expression_MaskExpression_ListSelect_ListSelectItem { 
    pb_size_t which_type;
    union {
        struct _substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListElement *item;
        struct _substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListSlice *slice;
    } type; 
} substrait_Expression_MaskExpression_ListSelect_ListSelectItem;

typedef struct _substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListElement { 
    int32_t *field; 
} substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListElement;

typedef struct _substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListSlice { 
    int32_t *start; 
    int32_t *end; 
} substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListSlice;

typedef struct _substrait_Expression_MaskExpression_MapSelect { 
    pb_size_t which_select;
    union {
        struct _substrait_Expression_MaskExpression_MapSelect_MapKey *key;
        struct _substrait_Expression_MaskExpression_MapSelect_MapKeyExpression *expression;
    } select; 
    struct _substrait_Expression_MaskExpression_Select *child; 
} substrait_Expression_MaskExpression_MapSelect;

typedef struct _substrait_Expression_MaskExpression_MapSelect_MapKey { 
    char *map_key; 
} substrait_Expression_MaskExpression_MapSelect_MapKey;

typedef struct _substrait_Expression_MaskExpression_MapSelect_MapKeyExpression { 
    char *map_key_expression; 
} substrait_Expression_MaskExpression_MapSelect_MapKeyExpression;

typedef struct _substrait_Expression_MaskExpression_Select { 
    pb_size_t which_type;
    union {
        struct _substrait_Expression_MaskExpression_StructSelect *struct_;
        struct _substrait_Expression_MaskExpression_ListSelect *list;
        struct _substrait_Expression_MaskExpression_MapSelect *map;
    } type; 
} substrait_Expression_MaskExpression_Select;

typedef struct _substrait_Expression_MaskExpression_StructItem { 
    int32_t *field; 
    struct _substrait_Expression_MaskExpression_Select *child; 
} substrait_Expression_MaskExpression_StructItem;

typedef struct _substrait_Expression_MaskExpression_StructSelect { 
    pb_size_t struct_items_count;
    struct _substrait_Expression_MaskExpression_StructItem *struct_items; 
} substrait_Expression_MaskExpression_StructSelect;

typedef struct _substrait_Expression_MultiOrList { 
    pb_size_t value_count;
    struct _substrait_Expression *value; 
    pb_size_t options_count;
    struct _substrait_Expression_MultiOrList_Record *options; 
} substrait_Expression_MultiOrList;

typedef struct _substrait_Expression_MultiOrList_Record { 
    pb_size_t fields_count;
    struct _substrait_Expression *fields; 
} substrait_Expression_MultiOrList_Record;

typedef struct _substrait_Expression_ReferenceSegment { 
    pb_size_t which_reference_type;
    union {
        struct _substrait_Expression_ReferenceSegment_MapKey *map_key;
        struct _substrait_Expression_ReferenceSegment_StructField *struct_field;
        struct _substrait_Expression_ReferenceSegment_ListElement *list_element;
    } reference_type; 
} substrait_Expression_ReferenceSegment;

typedef struct _substrait_Expression_ReferenceSegment_ListElement { 
    int32_t *offset; 
    struct _substrait_Expression_ReferenceSegment *child; 
} substrait_Expression_ReferenceSegment_ListElement;

typedef struct _substrait_Expression_ReferenceSegment_MapKey { 
    struct _substrait_Expression_Literal *map_key; 
    struct _substrait_Expression_ReferenceSegment *child; 
} substrait_Expression_ReferenceSegment_MapKey;

typedef struct _substrait_Expression_ReferenceSegment_StructField { 
    int32_t *field; 
    struct _substrait_Expression_ReferenceSegment *child; 
} substrait_Expression_ReferenceSegment_StructField;

typedef struct _substrait_Expression_ScalarFunction { 
    uint32_t *function_reference; 
    pb_size_t args_count;
    struct _substrait_Expression *args; 
    struct _substrait_Type *output_type; 
} substrait_Expression_ScalarFunction;

typedef struct _substrait_Expression_SingularOrList { 
    struct _substrait_Expression *value; 
    pb_size_t options_count;
    struct _substrait_Expression *options; 
} substrait_Expression_SingularOrList;

typedef struct _substrait_Expression_SwitchExpression { 
    pb_size_t ifs_count;
    struct _substrait_Expression_SwitchExpression_IfValue *ifs; 
    struct _substrait_Expression *else_; 
} substrait_Expression_SwitchExpression;

typedef struct _substrait_Expression_SwitchExpression_IfValue { 
    struct _substrait_Expression_Literal *if_; 
    struct _substrait_Expression *then; 
} substrait_Expression_SwitchExpression_IfValue;

typedef struct _substrait_Expression_WindowFunction { 
    uint32_t *function_reference; 
    pb_size_t partitions_count;
    struct _substrait_Expression *partitions; 
    pb_size_t sorts_count;
    struct _substrait_SortField *sorts; 
    struct _substrait_Expression_WindowFunction_Bound *upper_bound; 
    struct _substrait_Expression_WindowFunction_Bound *lower_bound; 
    substrait_AggregationPhase *phase; 
    struct _substrait_Type *output_type; 
    pb_size_t args_count;
    struct _substrait_Expression *args; 
} substrait_Expression_WindowFunction;

typedef struct _substrait_Expression_WindowFunction_Bound { 
    pb_size_t which_kind;
    union {
        struct _substrait_Expression_WindowFunction_Bound_Preceding *preceding;
        struct _substrait_Expression_WindowFunction_Bound_Following *following;
        struct _substrait_Expression_WindowFunction_Bound_CurrentRow *current_row;
        struct _substrait_Expression_WindowFunction_Bound_Unbounded *unbounded;
    } kind; 
} substrait_Expression_WindowFunction_Bound;

typedef struct _substrait_Expression_WindowFunction_Bound_CurrentRow { 
    char dummy_field;
} substrait_Expression_WindowFunction_Bound_CurrentRow;

typedef struct _substrait_Expression_WindowFunction_Bound_Following { 
    int64_t *offset; 
} substrait_Expression_WindowFunction_Bound_Following;

typedef struct _substrait_Expression_WindowFunction_Bound_Preceding { 
    int64_t *offset; 
} substrait_Expression_WindowFunction_Bound_Preceding;

typedef struct _substrait_Expression_WindowFunction_Bound_Unbounded { 
    char dummy_field;
} substrait_Expression_WindowFunction_Bound_Unbounded;

typedef struct _substrait_SortField { 
    struct _substrait_Expression *expr; 
    pb_size_t which_sort_kind;
    union {
        substrait_SortField_SortDirection *direction;
        uint32_t *comparison_function_reference;
    } sort_kind; 
} substrait_SortField;


/* Helper constants for enums */
#define _substrait_AggregationPhase_MIN substrait_AggregationPhase_AGGREGATION_PHASE_UNSPECIFIED
#define _substrait_AggregationPhase_MAX substrait_AggregationPhase_AGGREGATION_PHASE_INTERMEDIATE_TO_RESULT
#define _substrait_AggregationPhase_ARRAYSIZE ((substrait_AggregationPhase)(substrait_AggregationPhase_AGGREGATION_PHASE_INTERMEDIATE_TO_RESULT+1))

#define _substrait_SortField_SortDirection_MIN substrait_SortField_SortDirection_SORT_DIRECTION_UNSPECIFIED
#define _substrait_SortField_SortDirection_MAX substrait_SortField_SortDirection_SORT_DIRECTION_CLUSTERED
#define _substrait_SortField_SortDirection_ARRAYSIZE ((substrait_SortField_SortDirection)(substrait_SortField_SortDirection_SORT_DIRECTION_CLUSTERED+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define substrait_Expression_init_default        {0, {NULL}}
#define substrait_Expression_Enum_init_default   {0, {NULL}}
#define substrait_Expression_Enum_Empty_init_default {0}
#define substrait_Expression_Literal_init_default {0, {NULL}, NULL}
#define substrait_Expression_Literal_VarChar_init_default {NULL, NULL}
#define substrait_Expression_Literal_Decimal_init_default {NULL, NULL, NULL}
#define substrait_Expression_Literal_Map_init_default {0, NULL}
#define substrait_Expression_Literal_Map_KeyValue_init_default {NULL, NULL}
#define substrait_Expression_Literal_IntervalYearToMonth_init_default {NULL, NULL}
#define substrait_Expression_Literal_IntervalDayToSecond_init_default {NULL, NULL}
#define substrait_Expression_Literal_Struct_init_default {0, NULL}
#define substrait_Expression_Literal_List_init_default {0, NULL}
#define substrait_Expression_ScalarFunction_init_default {NULL, 0, NULL, NULL}
#define substrait_Expression_WindowFunction_init_default {NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL}
#define substrait_Expression_WindowFunction_Bound_init_default {0, {NULL}}
#define substrait_Expression_WindowFunction_Bound_Preceding_init_default {NULL}
#define substrait_Expression_WindowFunction_Bound_Following_init_default {NULL}
#define substrait_Expression_WindowFunction_Bound_CurrentRow_init_default {0}
#define substrait_Expression_WindowFunction_Bound_Unbounded_init_default {0}
#define substrait_Expression_IfThen_init_default {0, NULL, NULL}
#define substrait_Expression_IfThen_IfClause_init_default {NULL, NULL}
#define substrait_Expression_Cast_init_default   {NULL, NULL}
#define substrait_Expression_SwitchExpression_init_default {0, NULL, NULL}
#define substrait_Expression_SwitchExpression_IfValue_init_default {NULL, NULL}
#define substrait_Expression_SingularOrList_init_default {NULL, 0, NULL}
#define substrait_Expression_MultiOrList_init_default {0, NULL, 0, NULL}
#define substrait_Expression_MultiOrList_Record_init_default {0, NULL}
#define substrait_Expression_EmbeddedFunction_init_default {0, NULL, NULL, 0, {NULL}}
#define substrait_Expression_EmbeddedFunction_PythonPickleFunction_init_default {NULL, 0, NULL}
#define substrait_Expression_EmbeddedFunction_WebAssemblyFunction_init_default {NULL, 0, NULL}
#define substrait_Expression_ReferenceSegment_init_default {0, {NULL}}
#define substrait_Expression_ReferenceSegment_MapKey_init_default {NULL, NULL}
#define substrait_Expression_ReferenceSegment_StructField_init_default {NULL, NULL}
#define substrait_Expression_ReferenceSegment_ListElement_init_default {NULL, NULL}
#define substrait_Expression_MaskExpression_init_default {NULL, NULL}
#define substrait_Expression_MaskExpression_Select_init_default {0, {NULL}}
#define substrait_Expression_MaskExpression_StructSelect_init_default {0, NULL}
#define substrait_Expression_MaskExpression_StructItem_init_default {NULL, NULL}
#define substrait_Expression_MaskExpression_ListSelect_init_default {0, NULL, NULL}
#define substrait_Expression_MaskExpression_ListSelect_ListSelectItem_init_default {0, {NULL}}
#define substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListElement_init_default {NULL}
#define substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListSlice_init_default {NULL, NULL}
#define substrait_Expression_MaskExpression_MapSelect_init_default {0, {NULL}, NULL}
#define substrait_Expression_MaskExpression_MapSelect_MapKey_init_default {NULL}
#define substrait_Expression_MaskExpression_MapSelect_MapKeyExpression_init_default {NULL}
#define substrait_Expression_FieldReference_init_default {0, {NULL}, 0, {NULL}}
#define substrait_Expression_FieldReference_RootReference_init_default {0}
#define substrait_SortField_init_default         {NULL, 0, {NULL}}
#define substrait_AggregateFunction_init_default {NULL, 0, NULL, 0, NULL, NULL, NULL}
#define substrait_Expression_init_zero           {0, {NULL}}
#define substrait_Expression_Enum_init_zero      {0, {NULL}}
#define substrait_Expression_Enum_Empty_init_zero {0}
#define substrait_Expression_Literal_init_zero   {0, {NULL}, NULL}
#define substrait_Expression_Literal_VarChar_init_zero {NULL, NULL}
#define substrait_Expression_Literal_Decimal_init_zero {NULL, NULL, NULL}
#define substrait_Expression_Literal_Map_init_zero {0, NULL}
#define substrait_Expression_Literal_Map_KeyValue_init_zero {NULL, NULL}
#define substrait_Expression_Literal_IntervalYearToMonth_init_zero {NULL, NULL}
#define substrait_Expression_Literal_IntervalDayToSecond_init_zero {NULL, NULL}
#define substrait_Expression_Literal_Struct_init_zero {0, NULL}
#define substrait_Expression_Literal_List_init_zero {0, NULL}
#define substrait_Expression_ScalarFunction_init_zero {NULL, 0, NULL, NULL}
#define substrait_Expression_WindowFunction_init_zero {NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL}
#define substrait_Expression_WindowFunction_Bound_init_zero {0, {NULL}}
#define substrait_Expression_WindowFunction_Bound_Preceding_init_zero {NULL}
#define substrait_Expression_WindowFunction_Bound_Following_init_zero {NULL}
#define substrait_Expression_WindowFunction_Bound_CurrentRow_init_zero {0}
#define substrait_Expression_WindowFunction_Bound_Unbounded_init_zero {0}
#define substrait_Expression_IfThen_init_zero    {0, NULL, NULL}
#define substrait_Expression_IfThen_IfClause_init_zero {NULL, NULL}
#define substrait_Expression_Cast_init_zero      {NULL, NULL}
#define substrait_Expression_SwitchExpression_init_zero {0, NULL, NULL}
#define substrait_Expression_SwitchExpression_IfValue_init_zero {NULL, NULL}
#define substrait_Expression_SingularOrList_init_zero {NULL, 0, NULL}
#define substrait_Expression_MultiOrList_init_zero {0, NULL, 0, NULL}
#define substrait_Expression_MultiOrList_Record_init_zero {0, NULL}
#define substrait_Expression_EmbeddedFunction_init_zero {0, NULL, NULL, 0, {NULL}}
#define substrait_Expression_EmbeddedFunction_PythonPickleFunction_init_zero {NULL, 0, NULL}
#define substrait_Expression_EmbeddedFunction_WebAssemblyFunction_init_zero {NULL, 0, NULL}
#define substrait_Expression_ReferenceSegment_init_zero {0, {NULL}}
#define substrait_Expression_ReferenceSegment_MapKey_init_zero {NULL, NULL}
#define substrait_Expression_ReferenceSegment_StructField_init_zero {NULL, NULL}
#define substrait_Expression_ReferenceSegment_ListElement_init_zero {NULL, NULL}
#define substrait_Expression_MaskExpression_init_zero {NULL, NULL}
#define substrait_Expression_MaskExpression_Select_init_zero {0, {NULL}}
#define substrait_Expression_MaskExpression_StructSelect_init_zero {0, NULL}
#define substrait_Expression_MaskExpression_StructItem_init_zero {NULL, NULL}
#define substrait_Expression_MaskExpression_ListSelect_init_zero {0, NULL, NULL}
#define substrait_Expression_MaskExpression_ListSelect_ListSelectItem_init_zero {0, {NULL}}
#define substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListElement_init_zero {NULL}
#define substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListSlice_init_zero {NULL, NULL}
#define substrait_Expression_MaskExpression_MapSelect_init_zero {0, {NULL}, NULL}
#define substrait_Expression_MaskExpression_MapSelect_MapKey_init_zero {NULL}
#define substrait_Expression_MaskExpression_MapSelect_MapKeyExpression_init_zero {NULL}
#define substrait_Expression_FieldReference_init_zero {0, {NULL}, 0, {NULL}}
#define substrait_Expression_FieldReference_RootReference_init_zero {0}
#define substrait_SortField_init_zero            {NULL, 0, {NULL}}
#define substrait_AggregateFunction_init_zero    {NULL, 0, NULL, 0, NULL, NULL, NULL}

/* Field tags (for use in manual encoding/decoding) */
#define substrait_AggregateFunction_function_reference_tag 1
#define substrait_AggregateFunction_args_tag     2
#define substrait_AggregateFunction_sorts_tag    3
#define substrait_AggregateFunction_phase_tag    4
#define substrait_AggregateFunction_output_type_tag 5
#define substrait_Expression_literal_tag         1
#define substrait_Expression_selection_tag       2
#define substrait_Expression_scalar_function_tag 3
#define substrait_Expression_window_function_tag 5
#define substrait_Expression_if_then_tag         6
#define substrait_Expression_switch_expression_tag 7
#define substrait_Expression_singular_or_list_tag 8
#define substrait_Expression_multi_or_list_tag   9
#define substrait_Expression_enum__tag           10
#define substrait_Expression_cast_tag            11
#define substrait_Expression_Cast_type_tag       1
#define substrait_Expression_Cast_input_tag      2
#define substrait_Expression_EmbeddedFunction_arguments_tag 1
#define substrait_Expression_EmbeddedFunction_output_type_tag 2
#define substrait_Expression_EmbeddedFunction_python_pickle_function_tag 3
#define substrait_Expression_EmbeddedFunction_web_assembly_function_tag 4
#define substrait_Expression_EmbeddedFunction_PythonPickleFunction_function_tag 1
#define substrait_Expression_EmbeddedFunction_PythonPickleFunction_prerequisite_tag 2
#define substrait_Expression_EmbeddedFunction_WebAssemblyFunction_script_tag 1
#define substrait_Expression_EmbeddedFunction_WebAssemblyFunction_prerequisite_tag 2
#define substrait_Expression_Enum_specified_tag  1
#define substrait_Expression_Enum_unspecified_tag 2
#define substrait_Expression_FieldReference_direct_reference_tag 1
#define substrait_Expression_FieldReference_masked_reference_tag 2
#define substrait_Expression_FieldReference_expression_tag 3
#define substrait_Expression_FieldReference_root_reference_tag 4
#define substrait_Expression_IfThen_ifs_tag      1
#define substrait_Expression_IfThen_else__tag    2
#define substrait_Expression_IfThen_IfClause_if__tag 1
#define substrait_Expression_IfThen_IfClause_then_tag 2
#define substrait_Expression_Literal_boolean_tag 1
#define substrait_Expression_Literal_i8_tag      2
#define substrait_Expression_Literal_i16_tag     3
#define substrait_Expression_Literal_i32_tag     5
#define substrait_Expression_Literal_i64_tag     7
#define substrait_Expression_Literal_fp32_tag    10
#define substrait_Expression_Literal_fp64_tag    11
#define substrait_Expression_Literal_string_tag  12
#define substrait_Expression_Literal_binary_tag  13
#define substrait_Expression_Literal_timestamp_tag 14
#define substrait_Expression_Literal_date_tag    16
#define substrait_Expression_Literal_time_tag    17
#define substrait_Expression_Literal_interval_year_to_month_tag 19
#define substrait_Expression_Literal_interval_day_to_second_tag 20
#define substrait_Expression_Literal_fixed_char_tag 21
#define substrait_Expression_Literal_var_char_tag 22
#define substrait_Expression_Literal_fixed_binary_tag 23
#define substrait_Expression_Literal_decimal_tag 24
#define substrait_Expression_Literal_struct__tag 25
#define substrait_Expression_Literal_map_tag     26
#define substrait_Expression_Literal_timestamp_tz_tag 27
#define substrait_Expression_Literal_uuid_tag    28
#define substrait_Expression_Literal_null_tag    29
#define substrait_Expression_Literal_list_tag    30
#define substrait_Expression_Literal_empty_list_tag 31
#define substrait_Expression_Literal_empty_map_tag 32
#define substrait_Expression_Literal_nullable_tag 50
#define substrait_Expression_Literal_Decimal_value_tag 1
#define substrait_Expression_Literal_Decimal_precision_tag 2
#define substrait_Expression_Literal_Decimal_scale_tag 3
#define substrait_Expression_Literal_IntervalDayToSecond_days_tag 1
#define substrait_Expression_Literal_IntervalDayToSecond_seconds_tag 2
#define substrait_Expression_Literal_IntervalYearToMonth_years_tag 1
#define substrait_Expression_Literal_IntervalYearToMonth_months_tag 2
#define substrait_Expression_Literal_List_values_tag 1
#define substrait_Expression_Literal_Map_key_values_tag 1
#define substrait_Expression_Literal_Map_KeyValue_key_tag 1
#define substrait_Expression_Literal_Map_KeyValue_value_tag 2
#define substrait_Expression_Literal_Struct_fields_tag 1
#define substrait_Expression_Literal_VarChar_value_tag 1
#define substrait_Expression_Literal_VarChar_length_tag 2
#define substrait_Expression_MaskExpression_select_tag 1
#define substrait_Expression_MaskExpression_maintain_singular_struct_tag 2
#define substrait_Expression_MaskExpression_ListSelect_selection_tag 1
#define substrait_Expression_MaskExpression_ListSelect_child_tag 2
#define substrait_Expression_MaskExpression_ListSelect_ListSelectItem_item_tag 1
#define substrait_Expression_MaskExpression_ListSelect_ListSelectItem_slice_tag 2
#define substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListElement_field_tag 1
#define substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListSlice_start_tag 1
#define substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListSlice_end_tag 2
#define substrait_Expression_MaskExpression_MapSelect_key_tag 1
#define substrait_Expression_MaskExpression_MapSelect_expression_tag 2
#define substrait_Expression_MaskExpression_MapSelect_child_tag 3
#define substrait_Expression_MaskExpression_MapSelect_MapKey_map_key_tag 1
#define substrait_Expression_MaskExpression_MapSelect_MapKeyExpression_map_key_expression_tag 1
#define substrait_Expression_MaskExpression_Select_struct__tag 1
#define substrait_Expression_MaskExpression_Select_list_tag 2
#define substrait_Expression_MaskExpression_Select_map_tag 3
#define substrait_Expression_MaskExpression_StructItem_field_tag 1
#define substrait_Expression_MaskExpression_StructItem_child_tag 2
#define substrait_Expression_MaskExpression_StructSelect_struct_items_tag 1
#define substrait_Expression_MultiOrList_value_tag 1
#define substrait_Expression_MultiOrList_options_tag 2
#define substrait_Expression_MultiOrList_Record_fields_tag 1
#define substrait_Expression_ReferenceSegment_map_key_tag 1
#define substrait_Expression_ReferenceSegment_struct_field_tag 2
#define substrait_Expression_ReferenceSegment_list_element_tag 3
#define substrait_Expression_ReferenceSegment_ListElement_offset_tag 1
#define substrait_Expression_ReferenceSegment_ListElement_child_tag 2
#define substrait_Expression_ReferenceSegment_MapKey_map_key_tag 1
#define substrait_Expression_ReferenceSegment_MapKey_child_tag 2
#define substrait_Expression_ReferenceSegment_StructField_field_tag 1
#define substrait_Expression_ReferenceSegment_StructField_child_tag 2
#define substrait_Expression_ScalarFunction_function_reference_tag 1
#define substrait_Expression_ScalarFunction_args_tag 2
#define substrait_Expression_ScalarFunction_output_type_tag 3
#define substrait_Expression_SingularOrList_value_tag 1
#define substrait_Expression_SingularOrList_options_tag 2
#define substrait_Expression_SwitchExpression_ifs_tag 1
#define substrait_Expression_SwitchExpression_else__tag 2
#define substrait_Expression_SwitchExpression_IfValue_if__tag 1
#define substrait_Expression_SwitchExpression_IfValue_then_tag 2
#define substrait_Expression_WindowFunction_function_reference_tag 1
#define substrait_Expression_WindowFunction_partitions_tag 2
#define substrait_Expression_WindowFunction_sorts_tag 3
#define substrait_Expression_WindowFunction_upper_bound_tag 4
#define substrait_Expression_WindowFunction_lower_bound_tag 5
#define substrait_Expression_WindowFunction_phase_tag 6
#define substrait_Expression_WindowFunction_output_type_tag 7
#define substrait_Expression_WindowFunction_args_tag 8
#define substrait_Expression_WindowFunction_Bound_preceding_tag 1
#define substrait_Expression_WindowFunction_Bound_following_tag 2
#define substrait_Expression_WindowFunction_Bound_current_row_tag 3
#define substrait_Expression_WindowFunction_Bound_unbounded_tag 4
#define substrait_Expression_WindowFunction_Bound_Following_offset_tag 1
#define substrait_Expression_WindowFunction_Bound_Preceding_offset_tag 1
#define substrait_SortField_expr_tag             1
#define substrait_SortField_direction_tag        2
#define substrait_SortField_comparison_function_reference_tag 3

/* Struct field encoding specification for nanopb */
#define substrait_Expression_FIELDLIST(X, a) \
X(a, POINTER,  ONEOF,    MESSAGE,  (rex_type,literal,rex_type.literal),   1) \
X(a, POINTER,  ONEOF,    MESSAGE,  (rex_type,selection,rex_type.selection),   2) \
X(a, POINTER,  ONEOF,    MESSAGE,  (rex_type,scalar_function,rex_type.scalar_function),   3) \
X(a, POINTER,  ONEOF,    MESSAGE,  (rex_type,window_function,rex_type.window_function),   5) \
X(a, POINTER,  ONEOF,    MESSAGE,  (rex_type,if_then,rex_type.if_then),   6) \
X(a, POINTER,  ONEOF,    MESSAGE,  (rex_type,switch_expression,rex_type.switch_expression),   7) \
X(a, POINTER,  ONEOF,    MESSAGE,  (rex_type,singular_or_list,rex_type.singular_or_list),   8) \
X(a, POINTER,  ONEOF,    MESSAGE,  (rex_type,multi_or_list,rex_type.multi_or_list),   9) \
X(a, POINTER,  ONEOF,    MESSAGE,  (rex_type,enum_,rex_type.enum_),  10) \
X(a, POINTER,  ONEOF,    MESSAGE,  (rex_type,cast,rex_type.cast),  11)
#define substrait_Expression_CALLBACK NULL
#define substrait_Expression_DEFAULT NULL
#define substrait_Expression_rex_type_literal_MSGTYPE substrait_Expression_Literal
#define substrait_Expression_rex_type_selection_MSGTYPE substrait_Expression_FieldReference
#define substrait_Expression_rex_type_scalar_function_MSGTYPE substrait_Expression_ScalarFunction
#define substrait_Expression_rex_type_window_function_MSGTYPE substrait_Expression_WindowFunction
#define substrait_Expression_rex_type_if_then_MSGTYPE substrait_Expression_IfThen
#define substrait_Expression_rex_type_switch_expression_MSGTYPE substrait_Expression_SwitchExpression
#define substrait_Expression_rex_type_singular_or_list_MSGTYPE substrait_Expression_SingularOrList
#define substrait_Expression_rex_type_multi_or_list_MSGTYPE substrait_Expression_MultiOrList
#define substrait_Expression_rex_type_enum__MSGTYPE substrait_Expression_Enum
#define substrait_Expression_rex_type_cast_MSGTYPE substrait_Expression_Cast

#define substrait_Expression_Enum_FIELDLIST(X, a) \
X(a, POINTER,  ONEOF,    STRING,   (enum_kind,specified,enum_kind.specified),   1) \
X(a, POINTER,  ONEOF,    MESSAGE,  (enum_kind,unspecified,enum_kind.unspecified),   2)
#define substrait_Expression_Enum_CALLBACK NULL
#define substrait_Expression_Enum_DEFAULT NULL
#define substrait_Expression_Enum_enum_kind_unspecified_MSGTYPE substrait_Expression_Enum_Empty

#define substrait_Expression_Enum_Empty_FIELDLIST(X, a) \

#define substrait_Expression_Enum_Empty_CALLBACK NULL
#define substrait_Expression_Enum_Empty_DEFAULT NULL

#define substrait_Expression_Literal_FIELDLIST(X, a) \
X(a, POINTER,  ONEOF,    BOOL,     (literal_type,boolean,literal_type.boolean),   1) \
X(a, POINTER,  ONEOF,    INT32,    (literal_type,i8,literal_type.i8),   2) \
X(a, POINTER,  ONEOF,    INT32,    (literal_type,i16,literal_type.i16),   3) \
X(a, POINTER,  ONEOF,    INT32,    (literal_type,i32,literal_type.i32),   5) \
X(a, POINTER,  ONEOF,    INT64,    (literal_type,i64,literal_type.i64),   7) \
X(a, POINTER,  ONEOF,    FLOAT,    (literal_type,fp32,literal_type.fp32),  10) \
X(a, POINTER,  ONEOF,    DOUBLE,   (literal_type,fp64,literal_type.fp64),  11) \
X(a, POINTER,  ONEOF,    STRING,   (literal_type,string,literal_type.string),  12) \
X(a, POINTER,  ONEOF,    BYTES,    (literal_type,binary,literal_type.binary),  13) \
X(a, POINTER,  ONEOF,    INT64,    (literal_type,timestamp,literal_type.timestamp),  14) \
X(a, POINTER,  ONEOF,    INT32,    (literal_type,date,literal_type.date),  16) \
X(a, POINTER,  ONEOF,    INT64,    (literal_type,time,literal_type.time),  17) \
X(a, POINTER,  ONEOF,    MESSAGE,  (literal_type,interval_year_to_month,literal_type.interval_year_to_month),  19) \
X(a, POINTER,  ONEOF,    MESSAGE,  (literal_type,interval_day_to_second,literal_type.interval_day_to_second),  20) \
X(a, POINTER,  ONEOF,    STRING,   (literal_type,fixed_char,literal_type.fixed_char),  21) \
X(a, POINTER,  ONEOF,    MESSAGE,  (literal_type,var_char,literal_type.var_char),  22) \
X(a, POINTER,  ONEOF,    BYTES,    (literal_type,fixed_binary,literal_type.fixed_binary),  23) \
X(a, POINTER,  ONEOF,    MESSAGE,  (literal_type,decimal,literal_type.decimal),  24) \
X(a, POINTER,  ONEOF,    MESSAGE,  (literal_type,struct_,literal_type.struct_),  25) \
X(a, POINTER,  ONEOF,    MESSAGE,  (literal_type,map,literal_type.map),  26) \
X(a, POINTER,  ONEOF,    INT64,    (literal_type,timestamp_tz,literal_type.timestamp_tz),  27) \
X(a, POINTER,  ONEOF,    BYTES,    (literal_type,uuid,literal_type.uuid),  28) \
X(a, POINTER,  ONEOF,    MESSAGE,  (literal_type,null,literal_type.null),  29) \
X(a, POINTER,  ONEOF,    MESSAGE,  (literal_type,list,literal_type.list),  30) \
X(a, POINTER,  ONEOF,    MESSAGE,  (literal_type,empty_list,literal_type.empty_list),  31) \
X(a, POINTER,  ONEOF,    MESSAGE,  (literal_type,empty_map,literal_type.empty_map),  32) \
X(a, POINTER,  SINGULAR, BOOL,     nullable,         50)
#define substrait_Expression_Literal_CALLBACK NULL
#define substrait_Expression_Literal_DEFAULT NULL
#define substrait_Expression_Literal_literal_type_interval_year_to_month_MSGTYPE substrait_Expression_Literal_IntervalYearToMonth
#define substrait_Expression_Literal_literal_type_interval_day_to_second_MSGTYPE substrait_Expression_Literal_IntervalDayToSecond
#define substrait_Expression_Literal_literal_type_var_char_MSGTYPE substrait_Expression_Literal_VarChar
#define substrait_Expression_Literal_literal_type_decimal_MSGTYPE substrait_Expression_Literal_Decimal
#define substrait_Expression_Literal_literal_type_struct__MSGTYPE substrait_Expression_Literal_Struct
#define substrait_Expression_Literal_literal_type_map_MSGTYPE substrait_Expression_Literal_Map
#define substrait_Expression_Literal_literal_type_null_MSGTYPE substrait_Type
#define substrait_Expression_Literal_literal_type_list_MSGTYPE substrait_Expression_Literal_List
#define substrait_Expression_Literal_literal_type_empty_list_MSGTYPE substrait_Type_List
#define substrait_Expression_Literal_literal_type_empty_map_MSGTYPE substrait_Type_Map

#define substrait_Expression_Literal_VarChar_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   value,             1) \
X(a, POINTER,  SINGULAR, UINT32,   length,            2)
#define substrait_Expression_Literal_VarChar_CALLBACK NULL
#define substrait_Expression_Literal_VarChar_DEFAULT NULL

#define substrait_Expression_Literal_Decimal_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, BYTES,    value,             1) \
X(a, POINTER,  SINGULAR, INT32,    precision,         2) \
X(a, POINTER,  SINGULAR, INT32,    scale,             3)
#define substrait_Expression_Literal_Decimal_CALLBACK NULL
#define substrait_Expression_Literal_Decimal_DEFAULT NULL

#define substrait_Expression_Literal_Map_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  key_values,        1)
#define substrait_Expression_Literal_Map_CALLBACK NULL
#define substrait_Expression_Literal_Map_DEFAULT NULL
#define substrait_Expression_Literal_Map_key_values_MSGTYPE substrait_Expression_Literal_Map_KeyValue

#define substrait_Expression_Literal_Map_KeyValue_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  key,               1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  value,             2)
#define substrait_Expression_Literal_Map_KeyValue_CALLBACK NULL
#define substrait_Expression_Literal_Map_KeyValue_DEFAULT NULL
#define substrait_Expression_Literal_Map_KeyValue_key_MSGTYPE substrait_Expression_Literal
#define substrait_Expression_Literal_Map_KeyValue_value_MSGTYPE substrait_Expression_Literal

#define substrait_Expression_Literal_IntervalYearToMonth_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, INT32,    years,             1) \
X(a, POINTER,  SINGULAR, INT32,    months,            2)
#define substrait_Expression_Literal_IntervalYearToMonth_CALLBACK NULL
#define substrait_Expression_Literal_IntervalYearToMonth_DEFAULT NULL

#define substrait_Expression_Literal_IntervalDayToSecond_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, INT32,    days,              1) \
X(a, POINTER,  SINGULAR, INT32,    seconds,           2)
#define substrait_Expression_Literal_IntervalDayToSecond_CALLBACK NULL
#define substrait_Expression_Literal_IntervalDayToSecond_DEFAULT NULL

#define substrait_Expression_Literal_Struct_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  fields,            1)
#define substrait_Expression_Literal_Struct_CALLBACK NULL
#define substrait_Expression_Literal_Struct_DEFAULT NULL
#define substrait_Expression_Literal_Struct_fields_MSGTYPE substrait_Expression_Literal

#define substrait_Expression_Literal_List_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  values,            1)
#define substrait_Expression_Literal_List_CALLBACK NULL
#define substrait_Expression_Literal_List_DEFAULT NULL
#define substrait_Expression_Literal_List_values_MSGTYPE substrait_Expression_Literal

#define substrait_Expression_ScalarFunction_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, UINT32,   function_reference,   1) \
X(a, POINTER,  REPEATED, MESSAGE,  args,              2) \
X(a, POINTER,  OPTIONAL, MESSAGE,  output_type,       3)
#define substrait_Expression_ScalarFunction_CALLBACK NULL
#define substrait_Expression_ScalarFunction_DEFAULT NULL
#define substrait_Expression_ScalarFunction_args_MSGTYPE substrait_Expression
#define substrait_Expression_ScalarFunction_output_type_MSGTYPE substrait_Type

#define substrait_Expression_WindowFunction_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, UINT32,   function_reference,   1) \
X(a, POINTER,  REPEATED, MESSAGE,  partitions,        2) \
X(a, POINTER,  REPEATED, MESSAGE,  sorts,             3) \
X(a, POINTER,  OPTIONAL, MESSAGE,  upper_bound,       4) \
X(a, POINTER,  OPTIONAL, MESSAGE,  lower_bound,       5) \
X(a, POINTER,  SINGULAR, UENUM,    phase,             6) \
X(a, POINTER,  OPTIONAL, MESSAGE,  output_type,       7) \
X(a, POINTER,  REPEATED, MESSAGE,  args,              8)
#define substrait_Expression_WindowFunction_CALLBACK NULL
#define substrait_Expression_WindowFunction_DEFAULT NULL
#define substrait_Expression_WindowFunction_partitions_MSGTYPE substrait_Expression
#define substrait_Expression_WindowFunction_sorts_MSGTYPE substrait_SortField
#define substrait_Expression_WindowFunction_upper_bound_MSGTYPE substrait_Expression_WindowFunction_Bound
#define substrait_Expression_WindowFunction_lower_bound_MSGTYPE substrait_Expression_WindowFunction_Bound
#define substrait_Expression_WindowFunction_output_type_MSGTYPE substrait_Type
#define substrait_Expression_WindowFunction_args_MSGTYPE substrait_Expression

#define substrait_Expression_WindowFunction_Bound_FIELDLIST(X, a) \
X(a, POINTER,  ONEOF,    MESSAGE,  (kind,preceding,kind.preceding),   1) \
X(a, POINTER,  ONEOF,    MESSAGE,  (kind,following,kind.following),   2) \
X(a, POINTER,  ONEOF,    MESSAGE,  (kind,current_row,kind.current_row),   3) \
X(a, POINTER,  ONEOF,    MESSAGE,  (kind,unbounded,kind.unbounded),   4)
#define substrait_Expression_WindowFunction_Bound_CALLBACK NULL
#define substrait_Expression_WindowFunction_Bound_DEFAULT NULL
#define substrait_Expression_WindowFunction_Bound_kind_preceding_MSGTYPE substrait_Expression_WindowFunction_Bound_Preceding
#define substrait_Expression_WindowFunction_Bound_kind_following_MSGTYPE substrait_Expression_WindowFunction_Bound_Following
#define substrait_Expression_WindowFunction_Bound_kind_current_row_MSGTYPE substrait_Expression_WindowFunction_Bound_CurrentRow
#define substrait_Expression_WindowFunction_Bound_kind_unbounded_MSGTYPE substrait_Expression_WindowFunction_Bound_Unbounded

#define substrait_Expression_WindowFunction_Bound_Preceding_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, INT64,    offset,            1)
#define substrait_Expression_WindowFunction_Bound_Preceding_CALLBACK NULL
#define substrait_Expression_WindowFunction_Bound_Preceding_DEFAULT NULL

#define substrait_Expression_WindowFunction_Bound_Following_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, INT64,    offset,            1)
#define substrait_Expression_WindowFunction_Bound_Following_CALLBACK NULL
#define substrait_Expression_WindowFunction_Bound_Following_DEFAULT NULL

#define substrait_Expression_WindowFunction_Bound_CurrentRow_FIELDLIST(X, a) \

#define substrait_Expression_WindowFunction_Bound_CurrentRow_CALLBACK NULL
#define substrait_Expression_WindowFunction_Bound_CurrentRow_DEFAULT NULL

#define substrait_Expression_WindowFunction_Bound_Unbounded_FIELDLIST(X, a) \

#define substrait_Expression_WindowFunction_Bound_Unbounded_CALLBACK NULL
#define substrait_Expression_WindowFunction_Bound_Unbounded_DEFAULT NULL

#define substrait_Expression_IfThen_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  ifs,               1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  else_,             2)
#define substrait_Expression_IfThen_CALLBACK NULL
#define substrait_Expression_IfThen_DEFAULT NULL
#define substrait_Expression_IfThen_ifs_MSGTYPE substrait_Expression_IfThen_IfClause
#define substrait_Expression_IfThen_else__MSGTYPE substrait_Expression

#define substrait_Expression_IfThen_IfClause_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  if_,               1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  then,              2)
#define substrait_Expression_IfThen_IfClause_CALLBACK NULL
#define substrait_Expression_IfThen_IfClause_DEFAULT NULL
#define substrait_Expression_IfThen_IfClause_if__MSGTYPE substrait_Expression
#define substrait_Expression_IfThen_IfClause_then_MSGTYPE substrait_Expression

#define substrait_Expression_Cast_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  type,              1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  input,             2)
#define substrait_Expression_Cast_CALLBACK NULL
#define substrait_Expression_Cast_DEFAULT NULL
#define substrait_Expression_Cast_type_MSGTYPE substrait_Type
#define substrait_Expression_Cast_input_MSGTYPE substrait_Expression

#define substrait_Expression_SwitchExpression_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  ifs,               1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  else_,             2)
#define substrait_Expression_SwitchExpression_CALLBACK NULL
#define substrait_Expression_SwitchExpression_DEFAULT NULL
#define substrait_Expression_SwitchExpression_ifs_MSGTYPE substrait_Expression_SwitchExpression_IfValue
#define substrait_Expression_SwitchExpression_else__MSGTYPE substrait_Expression

#define substrait_Expression_SwitchExpression_IfValue_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  if_,               1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  then,              2)
#define substrait_Expression_SwitchExpression_IfValue_CALLBACK NULL
#define substrait_Expression_SwitchExpression_IfValue_DEFAULT NULL
#define substrait_Expression_SwitchExpression_IfValue_if__MSGTYPE substrait_Expression_Literal
#define substrait_Expression_SwitchExpression_IfValue_then_MSGTYPE substrait_Expression

#define substrait_Expression_SingularOrList_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  value,             1) \
X(a, POINTER,  REPEATED, MESSAGE,  options,           2)
#define substrait_Expression_SingularOrList_CALLBACK NULL
#define substrait_Expression_SingularOrList_DEFAULT NULL
#define substrait_Expression_SingularOrList_value_MSGTYPE substrait_Expression
#define substrait_Expression_SingularOrList_options_MSGTYPE substrait_Expression

#define substrait_Expression_MultiOrList_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  value,             1) \
X(a, POINTER,  REPEATED, MESSAGE,  options,           2)
#define substrait_Expression_MultiOrList_CALLBACK NULL
#define substrait_Expression_MultiOrList_DEFAULT NULL
#define substrait_Expression_MultiOrList_value_MSGTYPE substrait_Expression
#define substrait_Expression_MultiOrList_options_MSGTYPE substrait_Expression_MultiOrList_Record

#define substrait_Expression_MultiOrList_Record_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  fields,            1)
#define substrait_Expression_MultiOrList_Record_CALLBACK NULL
#define substrait_Expression_MultiOrList_Record_DEFAULT NULL
#define substrait_Expression_MultiOrList_Record_fields_MSGTYPE substrait_Expression

#define substrait_Expression_EmbeddedFunction_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  arguments,         1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  output_type,       2) \
X(a, POINTER,  ONEOF,    MESSAGE,  (kind,python_pickle_function,kind.python_pickle_function),   3) \
X(a, POINTER,  ONEOF,    MESSAGE,  (kind,web_assembly_function,kind.web_assembly_function),   4)
#define substrait_Expression_EmbeddedFunction_CALLBACK NULL
#define substrait_Expression_EmbeddedFunction_DEFAULT NULL
#define substrait_Expression_EmbeddedFunction_arguments_MSGTYPE substrait_Expression
#define substrait_Expression_EmbeddedFunction_output_type_MSGTYPE substrait_Type
#define substrait_Expression_EmbeddedFunction_kind_python_pickle_function_MSGTYPE substrait_Expression_EmbeddedFunction_PythonPickleFunction
#define substrait_Expression_EmbeddedFunction_kind_web_assembly_function_MSGTYPE substrait_Expression_EmbeddedFunction_WebAssemblyFunction

#define substrait_Expression_EmbeddedFunction_PythonPickleFunction_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, BYTES,    function,          1) \
X(a, POINTER,  REPEATED, STRING,   prerequisite,      2)
#define substrait_Expression_EmbeddedFunction_PythonPickleFunction_CALLBACK NULL
#define substrait_Expression_EmbeddedFunction_PythonPickleFunction_DEFAULT NULL

#define substrait_Expression_EmbeddedFunction_WebAssemblyFunction_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, BYTES,    script,            1) \
X(a, POINTER,  REPEATED, STRING,   prerequisite,      2)
#define substrait_Expression_EmbeddedFunction_WebAssemblyFunction_CALLBACK NULL
#define substrait_Expression_EmbeddedFunction_WebAssemblyFunction_DEFAULT NULL

#define substrait_Expression_ReferenceSegment_FIELDLIST(X, a) \
X(a, POINTER,  ONEOF,    MESSAGE,  (reference_type,map_key,reference_type.map_key),   1) \
X(a, POINTER,  ONEOF,    MESSAGE,  (reference_type,struct_field,reference_type.struct_field),   2) \
X(a, POINTER,  ONEOF,    MESSAGE,  (reference_type,list_element,reference_type.list_element),   3)
#define substrait_Expression_ReferenceSegment_CALLBACK NULL
#define substrait_Expression_ReferenceSegment_DEFAULT NULL
#define substrait_Expression_ReferenceSegment_reference_type_map_key_MSGTYPE substrait_Expression_ReferenceSegment_MapKey
#define substrait_Expression_ReferenceSegment_reference_type_struct_field_MSGTYPE substrait_Expression_ReferenceSegment_StructField
#define substrait_Expression_ReferenceSegment_reference_type_list_element_MSGTYPE substrait_Expression_ReferenceSegment_ListElement

#define substrait_Expression_ReferenceSegment_MapKey_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  map_key,           1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  child,             2)
#define substrait_Expression_ReferenceSegment_MapKey_CALLBACK NULL
#define substrait_Expression_ReferenceSegment_MapKey_DEFAULT NULL
#define substrait_Expression_ReferenceSegment_MapKey_map_key_MSGTYPE substrait_Expression_Literal
#define substrait_Expression_ReferenceSegment_MapKey_child_MSGTYPE substrait_Expression_ReferenceSegment

#define substrait_Expression_ReferenceSegment_StructField_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, INT32,    field,             1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  child,             2)
#define substrait_Expression_ReferenceSegment_StructField_CALLBACK NULL
#define substrait_Expression_ReferenceSegment_StructField_DEFAULT NULL
#define substrait_Expression_ReferenceSegment_StructField_child_MSGTYPE substrait_Expression_ReferenceSegment

#define substrait_Expression_ReferenceSegment_ListElement_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, INT32,    offset,            1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  child,             2)
#define substrait_Expression_ReferenceSegment_ListElement_CALLBACK NULL
#define substrait_Expression_ReferenceSegment_ListElement_DEFAULT NULL
#define substrait_Expression_ReferenceSegment_ListElement_child_MSGTYPE substrait_Expression_ReferenceSegment

#define substrait_Expression_MaskExpression_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  select,            1) \
X(a, POINTER,  SINGULAR, BOOL,     maintain_singular_struct,   2)
#define substrait_Expression_MaskExpression_CALLBACK NULL
#define substrait_Expression_MaskExpression_DEFAULT NULL
#define substrait_Expression_MaskExpression_select_MSGTYPE substrait_Expression_MaskExpression_StructSelect

#define substrait_Expression_MaskExpression_Select_FIELDLIST(X, a) \
X(a, POINTER,  ONEOF,    MESSAGE,  (type,struct_,type.struct_),   1) \
X(a, POINTER,  ONEOF,    MESSAGE,  (type,list,type.list),   2) \
X(a, POINTER,  ONEOF,    MESSAGE,  (type,map,type.map),   3)
#define substrait_Expression_MaskExpression_Select_CALLBACK NULL
#define substrait_Expression_MaskExpression_Select_DEFAULT NULL
#define substrait_Expression_MaskExpression_Select_type_struct__MSGTYPE substrait_Expression_MaskExpression_StructSelect
#define substrait_Expression_MaskExpression_Select_type_list_MSGTYPE substrait_Expression_MaskExpression_ListSelect
#define substrait_Expression_MaskExpression_Select_type_map_MSGTYPE substrait_Expression_MaskExpression_MapSelect

#define substrait_Expression_MaskExpression_StructSelect_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  struct_items,      1)
#define substrait_Expression_MaskExpression_StructSelect_CALLBACK NULL
#define substrait_Expression_MaskExpression_StructSelect_DEFAULT NULL
#define substrait_Expression_MaskExpression_StructSelect_struct_items_MSGTYPE substrait_Expression_MaskExpression_StructItem

#define substrait_Expression_MaskExpression_StructItem_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, INT32,    field,             1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  child,             2)
#define substrait_Expression_MaskExpression_StructItem_CALLBACK NULL
#define substrait_Expression_MaskExpression_StructItem_DEFAULT NULL
#define substrait_Expression_MaskExpression_StructItem_child_MSGTYPE substrait_Expression_MaskExpression_Select

#define substrait_Expression_MaskExpression_ListSelect_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  selection,         1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  child,             2)
#define substrait_Expression_MaskExpression_ListSelect_CALLBACK NULL
#define substrait_Expression_MaskExpression_ListSelect_DEFAULT NULL
#define substrait_Expression_MaskExpression_ListSelect_selection_MSGTYPE substrait_Expression_MaskExpression_ListSelect_ListSelectItem
#define substrait_Expression_MaskExpression_ListSelect_child_MSGTYPE substrait_Expression_MaskExpression_Select

#define substrait_Expression_MaskExpression_ListSelect_ListSelectItem_FIELDLIST(X, a) \
X(a, POINTER,  ONEOF,    MESSAGE,  (type,item,type.item),   1) \
X(a, POINTER,  ONEOF,    MESSAGE,  (type,slice,type.slice),   2)
#define substrait_Expression_MaskExpression_ListSelect_ListSelectItem_CALLBACK NULL
#define substrait_Expression_MaskExpression_ListSelect_ListSelectItem_DEFAULT NULL
#define substrait_Expression_MaskExpression_ListSelect_ListSelectItem_type_item_MSGTYPE substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListElement
#define substrait_Expression_MaskExpression_ListSelect_ListSelectItem_type_slice_MSGTYPE substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListSlice

#define substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListElement_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, INT32,    field,             1)
#define substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListElement_CALLBACK NULL
#define substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListElement_DEFAULT NULL

#define substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListSlice_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, INT32,    start,             1) \
X(a, POINTER,  SINGULAR, INT32,    end,               2)
#define substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListSlice_CALLBACK NULL
#define substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListSlice_DEFAULT NULL

#define substrait_Expression_MaskExpression_MapSelect_FIELDLIST(X, a) \
X(a, POINTER,  ONEOF,    MESSAGE,  (select,key,select.key),   1) \
X(a, POINTER,  ONEOF,    MESSAGE,  (select,expression,select.expression),   2) \
X(a, POINTER,  OPTIONAL, MESSAGE,  child,             3)
#define substrait_Expression_MaskExpression_MapSelect_CALLBACK NULL
#define substrait_Expression_MaskExpression_MapSelect_DEFAULT NULL
#define substrait_Expression_MaskExpression_MapSelect_select_key_MSGTYPE substrait_Expression_MaskExpression_MapSelect_MapKey
#define substrait_Expression_MaskExpression_MapSelect_select_expression_MSGTYPE substrait_Expression_MaskExpression_MapSelect_MapKeyExpression
#define substrait_Expression_MaskExpression_MapSelect_child_MSGTYPE substrait_Expression_MaskExpression_Select

#define substrait_Expression_MaskExpression_MapSelect_MapKey_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   map_key,           1)
#define substrait_Expression_MaskExpression_MapSelect_MapKey_CALLBACK NULL
#define substrait_Expression_MaskExpression_MapSelect_MapKey_DEFAULT NULL

#define substrait_Expression_MaskExpression_MapSelect_MapKeyExpression_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   map_key_expression,   1)
#define substrait_Expression_MaskExpression_MapSelect_MapKeyExpression_CALLBACK NULL
#define substrait_Expression_MaskExpression_MapSelect_MapKeyExpression_DEFAULT NULL

#define substrait_Expression_FieldReference_FIELDLIST(X, a) \
X(a, POINTER,  ONEOF,    MESSAGE,  (reference_type,direct_reference,reference_type.direct_reference),   1) \
X(a, POINTER,  ONEOF,    MESSAGE,  (reference_type,masked_reference,reference_type.masked_reference),   2) \
X(a, POINTER,  ONEOF,    MESSAGE,  (root_type,expression,root_type.expression),   3) \
X(a, POINTER,  ONEOF,    MESSAGE,  (root_type,root_reference,root_type.root_reference),   4)
#define substrait_Expression_FieldReference_CALLBACK NULL
#define substrait_Expression_FieldReference_DEFAULT NULL
#define substrait_Expression_FieldReference_reference_type_direct_reference_MSGTYPE substrait_Expression_ReferenceSegment
#define substrait_Expression_FieldReference_reference_type_masked_reference_MSGTYPE substrait_Expression_MaskExpression
#define substrait_Expression_FieldReference_root_type_expression_MSGTYPE substrait_Expression
#define substrait_Expression_FieldReference_root_type_root_reference_MSGTYPE substrait_Expression_FieldReference_RootReference

#define substrait_Expression_FieldReference_RootReference_FIELDLIST(X, a) \

#define substrait_Expression_FieldReference_RootReference_CALLBACK NULL
#define substrait_Expression_FieldReference_RootReference_DEFAULT NULL

#define substrait_SortField_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  expr,              1) \
X(a, POINTER,  ONEOF,    UENUM,    (sort_kind,direction,sort_kind.direction),   2) \
X(a, POINTER,  ONEOF,    UINT32,   (sort_kind,comparison_function_reference,sort_kind.comparison_function_reference),   3)
#define substrait_SortField_CALLBACK NULL
#define substrait_SortField_DEFAULT NULL
#define substrait_SortField_expr_MSGTYPE substrait_Expression

#define substrait_AggregateFunction_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, UINT32,   function_reference,   1) \
X(a, POINTER,  REPEATED, MESSAGE,  args,              2) \
X(a, POINTER,  REPEATED, MESSAGE,  sorts,             3) \
X(a, POINTER,  SINGULAR, UENUM,    phase,             4) \
X(a, POINTER,  OPTIONAL, MESSAGE,  output_type,       5)
#define substrait_AggregateFunction_CALLBACK NULL
#define substrait_AggregateFunction_DEFAULT NULL
#define substrait_AggregateFunction_args_MSGTYPE substrait_Expression
#define substrait_AggregateFunction_sorts_MSGTYPE substrait_SortField
#define substrait_AggregateFunction_output_type_MSGTYPE substrait_Type

extern const pb_msgdesc_t substrait_Expression_msg;
extern const pb_msgdesc_t substrait_Expression_Enum_msg;
extern const pb_msgdesc_t substrait_Expression_Enum_Empty_msg;
extern const pb_msgdesc_t substrait_Expression_Literal_msg;
extern const pb_msgdesc_t substrait_Expression_Literal_VarChar_msg;
extern const pb_msgdesc_t substrait_Expression_Literal_Decimal_msg;
extern const pb_msgdesc_t substrait_Expression_Literal_Map_msg;
extern const pb_msgdesc_t substrait_Expression_Literal_Map_KeyValue_msg;
extern const pb_msgdesc_t substrait_Expression_Literal_IntervalYearToMonth_msg;
extern const pb_msgdesc_t substrait_Expression_Literal_IntervalDayToSecond_msg;
extern const pb_msgdesc_t substrait_Expression_Literal_Struct_msg;
extern const pb_msgdesc_t substrait_Expression_Literal_List_msg;
extern const pb_msgdesc_t substrait_Expression_ScalarFunction_msg;
extern const pb_msgdesc_t substrait_Expression_WindowFunction_msg;
extern const pb_msgdesc_t substrait_Expression_WindowFunction_Bound_msg;
extern const pb_msgdesc_t substrait_Expression_WindowFunction_Bound_Preceding_msg;
extern const pb_msgdesc_t substrait_Expression_WindowFunction_Bound_Following_msg;
extern const pb_msgdesc_t substrait_Expression_WindowFunction_Bound_CurrentRow_msg;
extern const pb_msgdesc_t substrait_Expression_WindowFunction_Bound_Unbounded_msg;
extern const pb_msgdesc_t substrait_Expression_IfThen_msg;
extern const pb_msgdesc_t substrait_Expression_IfThen_IfClause_msg;
extern const pb_msgdesc_t substrait_Expression_Cast_msg;
extern const pb_msgdesc_t substrait_Expression_SwitchExpression_msg;
extern const pb_msgdesc_t substrait_Expression_SwitchExpression_IfValue_msg;
extern const pb_msgdesc_t substrait_Expression_SingularOrList_msg;
extern const pb_msgdesc_t substrait_Expression_MultiOrList_msg;
extern const pb_msgdesc_t substrait_Expression_MultiOrList_Record_msg;
extern const pb_msgdesc_t substrait_Expression_EmbeddedFunction_msg;
extern const pb_msgdesc_t substrait_Expression_EmbeddedFunction_PythonPickleFunction_msg;
extern const pb_msgdesc_t substrait_Expression_EmbeddedFunction_WebAssemblyFunction_msg;
extern const pb_msgdesc_t substrait_Expression_ReferenceSegment_msg;
extern const pb_msgdesc_t substrait_Expression_ReferenceSegment_MapKey_msg;
extern const pb_msgdesc_t substrait_Expression_ReferenceSegment_StructField_msg;
extern const pb_msgdesc_t substrait_Expression_ReferenceSegment_ListElement_msg;
extern const pb_msgdesc_t substrait_Expression_MaskExpression_msg;
extern const pb_msgdesc_t substrait_Expression_MaskExpression_Select_msg;
extern const pb_msgdesc_t substrait_Expression_MaskExpression_StructSelect_msg;
extern const pb_msgdesc_t substrait_Expression_MaskExpression_StructItem_msg;
extern const pb_msgdesc_t substrait_Expression_MaskExpression_ListSelect_msg;
extern const pb_msgdesc_t substrait_Expression_MaskExpression_ListSelect_ListSelectItem_msg;
extern const pb_msgdesc_t substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListElement_msg;
extern const pb_msgdesc_t substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListSlice_msg;
extern const pb_msgdesc_t substrait_Expression_MaskExpression_MapSelect_msg;
extern const pb_msgdesc_t substrait_Expression_MaskExpression_MapSelect_MapKey_msg;
extern const pb_msgdesc_t substrait_Expression_MaskExpression_MapSelect_MapKeyExpression_msg;
extern const pb_msgdesc_t substrait_Expression_FieldReference_msg;
extern const pb_msgdesc_t substrait_Expression_FieldReference_RootReference_msg;
extern const pb_msgdesc_t substrait_SortField_msg;
extern const pb_msgdesc_t substrait_AggregateFunction_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define substrait_Expression_fields &substrait_Expression_msg
#define substrait_Expression_Enum_fields &substrait_Expression_Enum_msg
#define substrait_Expression_Enum_Empty_fields &substrait_Expression_Enum_Empty_msg
#define substrait_Expression_Literal_fields &substrait_Expression_Literal_msg
#define substrait_Expression_Literal_VarChar_fields &substrait_Expression_Literal_VarChar_msg
#define substrait_Expression_Literal_Decimal_fields &substrait_Expression_Literal_Decimal_msg
#define substrait_Expression_Literal_Map_fields &substrait_Expression_Literal_Map_msg
#define substrait_Expression_Literal_Map_KeyValue_fields &substrait_Expression_Literal_Map_KeyValue_msg
#define substrait_Expression_Literal_IntervalYearToMonth_fields &substrait_Expression_Literal_IntervalYearToMonth_msg
#define substrait_Expression_Literal_IntervalDayToSecond_fields &substrait_Expression_Literal_IntervalDayToSecond_msg
#define substrait_Expression_Literal_Struct_fields &substrait_Expression_Literal_Struct_msg
#define substrait_Expression_Literal_List_fields &substrait_Expression_Literal_List_msg
#define substrait_Expression_ScalarFunction_fields &substrait_Expression_ScalarFunction_msg
#define substrait_Expression_WindowFunction_fields &substrait_Expression_WindowFunction_msg
#define substrait_Expression_WindowFunction_Bound_fields &substrait_Expression_WindowFunction_Bound_msg
#define substrait_Expression_WindowFunction_Bound_Preceding_fields &substrait_Expression_WindowFunction_Bound_Preceding_msg
#define substrait_Expression_WindowFunction_Bound_Following_fields &substrait_Expression_WindowFunction_Bound_Following_msg
#define substrait_Expression_WindowFunction_Bound_CurrentRow_fields &substrait_Expression_WindowFunction_Bound_CurrentRow_msg
#define substrait_Expression_WindowFunction_Bound_Unbounded_fields &substrait_Expression_WindowFunction_Bound_Unbounded_msg
#define substrait_Expression_IfThen_fields &substrait_Expression_IfThen_msg
#define substrait_Expression_IfThen_IfClause_fields &substrait_Expression_IfThen_IfClause_msg
#define substrait_Expression_Cast_fields &substrait_Expression_Cast_msg
#define substrait_Expression_SwitchExpression_fields &substrait_Expression_SwitchExpression_msg
#define substrait_Expression_SwitchExpression_IfValue_fields &substrait_Expression_SwitchExpression_IfValue_msg
#define substrait_Expression_SingularOrList_fields &substrait_Expression_SingularOrList_msg
#define substrait_Expression_MultiOrList_fields &substrait_Expression_MultiOrList_msg
#define substrait_Expression_MultiOrList_Record_fields &substrait_Expression_MultiOrList_Record_msg
#define substrait_Expression_EmbeddedFunction_fields &substrait_Expression_EmbeddedFunction_msg
#define substrait_Expression_EmbeddedFunction_PythonPickleFunction_fields &substrait_Expression_EmbeddedFunction_PythonPickleFunction_msg
#define substrait_Expression_EmbeddedFunction_WebAssemblyFunction_fields &substrait_Expression_EmbeddedFunction_WebAssemblyFunction_msg
#define substrait_Expression_ReferenceSegment_fields &substrait_Expression_ReferenceSegment_msg
#define substrait_Expression_ReferenceSegment_MapKey_fields &substrait_Expression_ReferenceSegment_MapKey_msg
#define substrait_Expression_ReferenceSegment_StructField_fields &substrait_Expression_ReferenceSegment_StructField_msg
#define substrait_Expression_ReferenceSegment_ListElement_fields &substrait_Expression_ReferenceSegment_ListElement_msg
#define substrait_Expression_MaskExpression_fields &substrait_Expression_MaskExpression_msg
#define substrait_Expression_MaskExpression_Select_fields &substrait_Expression_MaskExpression_Select_msg
#define substrait_Expression_MaskExpression_StructSelect_fields &substrait_Expression_MaskExpression_StructSelect_msg
#define substrait_Expression_MaskExpression_StructItem_fields &substrait_Expression_MaskExpression_StructItem_msg
#define substrait_Expression_MaskExpression_ListSelect_fields &substrait_Expression_MaskExpression_ListSelect_msg
#define substrait_Expression_MaskExpression_ListSelect_ListSelectItem_fields &substrait_Expression_MaskExpression_ListSelect_ListSelectItem_msg
#define substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListElement_fields &substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListElement_msg
#define substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListSlice_fields &substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListSlice_msg
#define substrait_Expression_MaskExpression_MapSelect_fields &substrait_Expression_MaskExpression_MapSelect_msg
#define substrait_Expression_MaskExpression_MapSelect_MapKey_fields &substrait_Expression_MaskExpression_MapSelect_MapKey_msg
#define substrait_Expression_MaskExpression_MapSelect_MapKeyExpression_fields &substrait_Expression_MaskExpression_MapSelect_MapKeyExpression_msg
#define substrait_Expression_FieldReference_fields &substrait_Expression_FieldReference_msg
#define substrait_Expression_FieldReference_RootReference_fields &substrait_Expression_FieldReference_RootReference_msg
#define substrait_SortField_fields &substrait_SortField_msg
#define substrait_AggregateFunction_fields &substrait_AggregateFunction_msg

/* Maximum encoded size of messages (where known) */
/* substrait_Expression_size depends on runtime parameters */
/* substrait_Expression_Enum_size depends on runtime parameters */
/* substrait_Expression_Literal_size depends on runtime parameters */
/* substrait_Expression_Literal_VarChar_size depends on runtime parameters */
/* substrait_Expression_Literal_Decimal_size depends on runtime parameters */
/* substrait_Expression_Literal_Map_size depends on runtime parameters */
/* substrait_Expression_Literal_Map_KeyValue_size depends on runtime parameters */
/* substrait_Expression_Literal_IntervalYearToMonth_size depends on runtime parameters */
/* substrait_Expression_Literal_IntervalDayToSecond_size depends on runtime parameters */
/* substrait_Expression_Literal_Struct_size depends on runtime parameters */
/* substrait_Expression_Literal_List_size depends on runtime parameters */
/* substrait_Expression_ScalarFunction_size depends on runtime parameters */
/* substrait_Expression_WindowFunction_size depends on runtime parameters */
/* substrait_Expression_WindowFunction_Bound_size depends on runtime parameters */
/* substrait_Expression_WindowFunction_Bound_Preceding_size depends on runtime parameters */
/* substrait_Expression_WindowFunction_Bound_Following_size depends on runtime parameters */
/* substrait_Expression_IfThen_size depends on runtime parameters */
/* substrait_Expression_IfThen_IfClause_size depends on runtime parameters */
/* substrait_Expression_Cast_size depends on runtime parameters */
/* substrait_Expression_SwitchExpression_size depends on runtime parameters */
/* substrait_Expression_SwitchExpression_IfValue_size depends on runtime parameters */
/* substrait_Expression_SingularOrList_size depends on runtime parameters */
/* substrait_Expression_MultiOrList_size depends on runtime parameters */
/* substrait_Expression_MultiOrList_Record_size depends on runtime parameters */
/* substrait_Expression_EmbeddedFunction_size depends on runtime parameters */
/* substrait_Expression_EmbeddedFunction_PythonPickleFunction_size depends on runtime parameters */
/* substrait_Expression_EmbeddedFunction_WebAssemblyFunction_size depends on runtime parameters */
/* substrait_Expression_ReferenceSegment_size depends on runtime parameters */
/* substrait_Expression_ReferenceSegment_MapKey_size depends on runtime parameters */
/* substrait_Expression_ReferenceSegment_StructField_size depends on runtime parameters */
/* substrait_Expression_ReferenceSegment_ListElement_size depends on runtime parameters */
/* substrait_Expression_MaskExpression_size depends on runtime parameters */
/* substrait_Expression_MaskExpression_Select_size depends on runtime parameters */
/* substrait_Expression_MaskExpression_StructSelect_size depends on runtime parameters */
/* substrait_Expression_MaskExpression_StructItem_size depends on runtime parameters */
/* substrait_Expression_MaskExpression_ListSelect_size depends on runtime parameters */
/* substrait_Expression_MaskExpression_ListSelect_ListSelectItem_size depends on runtime parameters */
/* substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListElement_size depends on runtime parameters */
/* substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListSlice_size depends on runtime parameters */
/* substrait_Expression_MaskExpression_MapSelect_size depends on runtime parameters */
/* substrait_Expression_MaskExpression_MapSelect_MapKey_size depends on runtime parameters */
/* substrait_Expression_MaskExpression_MapSelect_MapKeyExpression_size depends on runtime parameters */
/* substrait_Expression_FieldReference_size depends on runtime parameters */
/* substrait_SortField_size depends on runtime parameters */
/* substrait_AggregateFunction_size depends on runtime parameters */
#define substrait_Expression_Enum_Empty_size     0
#define substrait_Expression_FieldReference_RootReference_size 0
#define substrait_Expression_WindowFunction_Bound_CurrentRow_size 0
#define substrait_Expression_WindowFunction_Bound_Unbounded_size 0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
