/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_SUBSTRAIT_SUBSTRAIT_FUNCTION_PB_H_INCLUDED
#define PB_SUBSTRAIT_SUBSTRAIT_FUNCTION_PB_H_INCLUDED
#include <pb.h>
#include "substrait/type.pb.h"
#include "substrait/parameterized_types.pb.h"
#include "substrait/type_expressions.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _substrait_FunctionSignature_FinalArgVariadic_ParameterConsistency { 
    substrait_FunctionSignature_FinalArgVariadic_ParameterConsistency_PARAMETER_CONSISTENCY_UNSPECIFIED = 0, 
    substrait_FunctionSignature_FinalArgVariadic_ParameterConsistency_PARAMETER_CONSISTENCY_CONSISTENT = 1, 
    substrait_FunctionSignature_FinalArgVariadic_ParameterConsistency_PARAMETER_CONSISTENCY_INCONSISTENT = 2 
} substrait_FunctionSignature_FinalArgVariadic_ParameterConsistency;

typedef enum _substrait_FunctionSignature_Window_WindowType { 
    substrait_FunctionSignature_Window_WindowType_WINDOW_TYPE_UNSPECIFIED = 0, 
    substrait_FunctionSignature_Window_WindowType_WINDOW_TYPE_STREAMING = 1, 
    substrait_FunctionSignature_Window_WindowType_WINDOW_TYPE_PARTITION = 2 
} substrait_FunctionSignature_Window_WindowType;

typedef enum _substrait_FunctionSignature_Implementation_Type { 
    substrait_FunctionSignature_Implementation_Type_TYPE_UNSPECIFIED = 0, 
    substrait_FunctionSignature_Implementation_Type_TYPE_WEB_ASSEMBLY = 1, 
    substrait_FunctionSignature_Implementation_Type_TYPE_TRINO_JAR = 2 
} substrait_FunctionSignature_Implementation_Type;

/* Struct definitions */
/* List of function signatures available. */
typedef struct _substrait_FunctionSignature { 
    char dummy_field;
} substrait_FunctionSignature;

typedef struct _substrait_FunctionSignature_Aggregate { 
    pb_callback_t arguments; 
    pb_callback_t name; 
    pb_callback_t description; 
    pb_callback_t deterministic; 
    pb_callback_t session_dependent; 
    pb_callback_t output_type; 
    pb_size_t which_final_variable_behavior;
    union {
        pb_callback_t variadic;
        pb_callback_t normal;
    } final_variable_behavior; 
    pb_callback_t max_set; 
    pb_callback_t intermediate_type; 
    pb_callback_t ordered; 
    pb_callback_t implementations; 
} substrait_FunctionSignature_Aggregate;

typedef struct _substrait_FunctionSignature_Argument { 
    pb_callback_t name; 
    pb_size_t which_argument_kind;
    union {
        pb_callback_t value;
        pb_callback_t type;
        pb_callback_t enum_;
    } argument_kind; 
} substrait_FunctionSignature_Argument;

typedef struct _substrait_FunctionSignature_Argument_EnumArgument { 
    pb_callback_t options; 
    pb_callback_t optional; 
} substrait_FunctionSignature_Argument_EnumArgument;

typedef struct _substrait_FunctionSignature_Argument_TypeArgument { 
    pb_callback_t type; 
} substrait_FunctionSignature_Argument_TypeArgument;

typedef struct _substrait_FunctionSignature_Argument_ValueArgument { 
    pb_callback_t type; 
    pb_callback_t constant; 
} substrait_FunctionSignature_Argument_ValueArgument;

typedef struct _substrait_FunctionSignature_Description { 
    pb_callback_t language; 
    pb_callback_t body; 
} substrait_FunctionSignature_Description;

typedef struct _substrait_FunctionSignature_FinalArgNormal { 
    char dummy_field;
} substrait_FunctionSignature_FinalArgNormal;

typedef struct _substrait_FunctionSignature_FinalArgVariadic { 
    pb_callback_t min_args; 
    pb_callback_t max_args; 
    pb_callback_t consistency; 
} substrait_FunctionSignature_FinalArgVariadic;

typedef struct _substrait_FunctionSignature_Implementation { 
    pb_callback_t type; 
    pb_callback_t uri; 
} substrait_FunctionSignature_Implementation;

typedef struct _substrait_FunctionSignature_Scalar { 
    pb_callback_t arguments; 
    pb_callback_t name; 
    pb_callback_t description; 
    pb_callback_t deterministic; 
    pb_callback_t session_dependent; 
    pb_callback_t output_type; 
    pb_size_t which_final_variable_behavior;
    union {
        pb_callback_t variadic;
        pb_callback_t normal;
    } final_variable_behavior; 
    pb_callback_t implementations; 
} substrait_FunctionSignature_Scalar;

typedef struct _substrait_FunctionSignature_Window { 
    pb_callback_t arguments; 
    pb_callback_t name; 
    pb_callback_t description; 
    pb_callback_t deterministic; 
    pb_callback_t session_dependent; 
    pb_callback_t intermediate_type; 
    pb_callback_t output_type; 
    pb_callback_t ordered; 
    pb_callback_t max_set; 
    pb_callback_t window_type; 
    pb_callback_t implementations; 
    pb_size_t which_final_variable_behavior;
    union {
        pb_callback_t variadic;
        pb_callback_t normal;
    } final_variable_behavior; 
} substrait_FunctionSignature_Window;


/* Helper constants for enums */
#define _substrait_FunctionSignature_FinalArgVariadic_ParameterConsistency_MIN substrait_FunctionSignature_FinalArgVariadic_ParameterConsistency_PARAMETER_CONSISTENCY_UNSPECIFIED
#define _substrait_FunctionSignature_FinalArgVariadic_ParameterConsistency_MAX substrait_FunctionSignature_FinalArgVariadic_ParameterConsistency_PARAMETER_CONSISTENCY_INCONSISTENT
#define _substrait_FunctionSignature_FinalArgVariadic_ParameterConsistency_ARRAYSIZE ((substrait_FunctionSignature_FinalArgVariadic_ParameterConsistency)(substrait_FunctionSignature_FinalArgVariadic_ParameterConsistency_PARAMETER_CONSISTENCY_INCONSISTENT+1))

#define _substrait_FunctionSignature_Window_WindowType_MIN substrait_FunctionSignature_Window_WindowType_WINDOW_TYPE_UNSPECIFIED
#define _substrait_FunctionSignature_Window_WindowType_MAX substrait_FunctionSignature_Window_WindowType_WINDOW_TYPE_PARTITION
#define _substrait_FunctionSignature_Window_WindowType_ARRAYSIZE ((substrait_FunctionSignature_Window_WindowType)(substrait_FunctionSignature_Window_WindowType_WINDOW_TYPE_PARTITION+1))

#define _substrait_FunctionSignature_Implementation_Type_MIN substrait_FunctionSignature_Implementation_Type_TYPE_UNSPECIFIED
#define _substrait_FunctionSignature_Implementation_Type_MAX substrait_FunctionSignature_Implementation_Type_TYPE_TRINO_JAR
#define _substrait_FunctionSignature_Implementation_Type_ARRAYSIZE ((substrait_FunctionSignature_Implementation_Type)(substrait_FunctionSignature_Implementation_Type_TYPE_TRINO_JAR+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define substrait_FunctionSignature_init_default {0}
#define substrait_FunctionSignature_FinalArgVariadic_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_FunctionSignature_FinalArgNormal_init_default {0}
#define substrait_FunctionSignature_Scalar_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{{NULL}, NULL}}, {{NULL}, NULL}}
#define substrait_FunctionSignature_Aggregate_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{{NULL}, NULL}}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_FunctionSignature_Window_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{{NULL}, NULL}}}
#define substrait_FunctionSignature_Description_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_FunctionSignature_Implementation_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_FunctionSignature_Argument_init_default {{{NULL}, NULL}, 0, {{{NULL}, NULL}}}
#define substrait_FunctionSignature_Argument_ValueArgument_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_FunctionSignature_Argument_TypeArgument_init_default {{{NULL}, NULL}}
#define substrait_FunctionSignature_Argument_EnumArgument_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_FunctionSignature_init_zero    {0}
#define substrait_FunctionSignature_FinalArgVariadic_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_FunctionSignature_FinalArgNormal_init_zero {0}
#define substrait_FunctionSignature_Scalar_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{{NULL}, NULL}}, {{NULL}, NULL}}
#define substrait_FunctionSignature_Aggregate_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{{NULL}, NULL}}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_FunctionSignature_Window_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{{NULL}, NULL}}}
#define substrait_FunctionSignature_Description_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_FunctionSignature_Implementation_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_FunctionSignature_Argument_init_zero {{{NULL}, NULL}, 0, {{{NULL}, NULL}}}
#define substrait_FunctionSignature_Argument_ValueArgument_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_FunctionSignature_Argument_TypeArgument_init_zero {{{NULL}, NULL}}
#define substrait_FunctionSignature_Argument_EnumArgument_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define substrait_FunctionSignature_Aggregate_arguments_tag 2
#define substrait_FunctionSignature_Aggregate_name_tag 3
#define substrait_FunctionSignature_Aggregate_description_tag 4
#define substrait_FunctionSignature_Aggregate_deterministic_tag 7
#define substrait_FunctionSignature_Aggregate_session_dependent_tag 8
#define substrait_FunctionSignature_Aggregate_output_type_tag 9
#define substrait_FunctionSignature_Aggregate_variadic_tag 10
#define substrait_FunctionSignature_Aggregate_normal_tag 11
#define substrait_FunctionSignature_Aggregate_max_set_tag 12
#define substrait_FunctionSignature_Aggregate_intermediate_type_tag 13
#define substrait_FunctionSignature_Aggregate_ordered_tag 14
#define substrait_FunctionSignature_Aggregate_implementations_tag 15
#define substrait_FunctionSignature_Argument_name_tag 1
#define substrait_FunctionSignature_Argument_value_tag 2
#define substrait_FunctionSignature_Argument_type_tag 3
#define substrait_FunctionSignature_Argument_enum__tag 4
#define substrait_FunctionSignature_Argument_EnumArgument_options_tag 1
#define substrait_FunctionSignature_Argument_EnumArgument_optional_tag 2
#define substrait_FunctionSignature_Argument_TypeArgument_type_tag 1
#define substrait_FunctionSignature_Argument_ValueArgument_type_tag 1
#define substrait_FunctionSignature_Argument_ValueArgument_constant_tag 2
#define substrait_FunctionSignature_Description_language_tag 1
#define substrait_FunctionSignature_Description_body_tag 2
#define substrait_FunctionSignature_FinalArgVariadic_min_args_tag 1
#define substrait_FunctionSignature_FinalArgVariadic_max_args_tag 2
#define substrait_FunctionSignature_FinalArgVariadic_consistency_tag 3
#define substrait_FunctionSignature_Implementation_type_tag 1
#define substrait_FunctionSignature_Implementation_uri_tag 2
#define substrait_FunctionSignature_Scalar_arguments_tag 2
#define substrait_FunctionSignature_Scalar_name_tag 3
#define substrait_FunctionSignature_Scalar_description_tag 4
#define substrait_FunctionSignature_Scalar_deterministic_tag 7
#define substrait_FunctionSignature_Scalar_session_dependent_tag 8
#define substrait_FunctionSignature_Scalar_output_type_tag 9
#define substrait_FunctionSignature_Scalar_variadic_tag 10
#define substrait_FunctionSignature_Scalar_normal_tag 11
#define substrait_FunctionSignature_Scalar_implementations_tag 12
#define substrait_FunctionSignature_Window_arguments_tag 2
#define substrait_FunctionSignature_Window_name_tag 3
#define substrait_FunctionSignature_Window_description_tag 4
#define substrait_FunctionSignature_Window_deterministic_tag 7
#define substrait_FunctionSignature_Window_session_dependent_tag 8
#define substrait_FunctionSignature_Window_intermediate_type_tag 9
#define substrait_FunctionSignature_Window_output_type_tag 10
#define substrait_FunctionSignature_Window_ordered_tag 11
#define substrait_FunctionSignature_Window_max_set_tag 12
#define substrait_FunctionSignature_Window_window_type_tag 14
#define substrait_FunctionSignature_Window_implementations_tag 15
#define substrait_FunctionSignature_Window_variadic_tag 16
#define substrait_FunctionSignature_Window_normal_tag 17

/* Struct field encoding specification for nanopb */
#define substrait_FunctionSignature_FIELDLIST(X, a) \

#define substrait_FunctionSignature_CALLBACK NULL
#define substrait_FunctionSignature_DEFAULT NULL

#define substrait_FunctionSignature_FinalArgVariadic_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, INT64,    min_args,          1) \
X(a, CALLBACK, SINGULAR, INT64,    max_args,          2) \
X(a, CALLBACK, SINGULAR, UENUM,    consistency,       3)
#define substrait_FunctionSignature_FinalArgVariadic_CALLBACK pb_default_field_callback
#define substrait_FunctionSignature_FinalArgVariadic_DEFAULT NULL

#define substrait_FunctionSignature_FinalArgNormal_FIELDLIST(X, a) \

#define substrait_FunctionSignature_FinalArgNormal_CALLBACK NULL
#define substrait_FunctionSignature_FinalArgNormal_DEFAULT NULL

#define substrait_FunctionSignature_Scalar_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  arguments,         2) \
X(a, CALLBACK, REPEATED, STRING,   name,              3) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  description,       4) \
X(a, CALLBACK, SINGULAR, BOOL,     deterministic,     7) \
X(a, CALLBACK, SINGULAR, BOOL,     session_dependent,   8) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  output_type,       9) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (final_variable_behavior,variadic,final_variable_behavior.variadic),  10) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (final_variable_behavior,normal,final_variable_behavior.normal),  11) \
X(a, CALLBACK, REPEATED, MESSAGE,  implementations,  12)
#define substrait_FunctionSignature_Scalar_CALLBACK pb_default_field_callback
#define substrait_FunctionSignature_Scalar_DEFAULT NULL
#define substrait_FunctionSignature_Scalar_arguments_MSGTYPE substrait_FunctionSignature_Argument
#define substrait_FunctionSignature_Scalar_description_MSGTYPE substrait_FunctionSignature_Description
#define substrait_FunctionSignature_Scalar_output_type_MSGTYPE substrait_DerivationExpression
#define substrait_FunctionSignature_Scalar_final_variable_behavior_variadic_MSGTYPE substrait_FunctionSignature_FinalArgVariadic
#define substrait_FunctionSignature_Scalar_final_variable_behavior_normal_MSGTYPE substrait_FunctionSignature_FinalArgNormal
#define substrait_FunctionSignature_Scalar_implementations_MSGTYPE substrait_FunctionSignature_Implementation

#define substrait_FunctionSignature_Aggregate_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  arguments,         2) \
X(a, CALLBACK, SINGULAR, STRING,   name,              3) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  description,       4) \
X(a, CALLBACK, SINGULAR, BOOL,     deterministic,     7) \
X(a, CALLBACK, SINGULAR, BOOL,     session_dependent,   8) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  output_type,       9) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (final_variable_behavior,variadic,final_variable_behavior.variadic),  10) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (final_variable_behavior,normal,final_variable_behavior.normal),  11) \
X(a, CALLBACK, SINGULAR, UINT64,   max_set,          12) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  intermediate_type,  13) \
X(a, CALLBACK, SINGULAR, BOOL,     ordered,          14) \
X(a, CALLBACK, REPEATED, MESSAGE,  implementations,  15)
#define substrait_FunctionSignature_Aggregate_CALLBACK pb_default_field_callback
#define substrait_FunctionSignature_Aggregate_DEFAULT NULL
#define substrait_FunctionSignature_Aggregate_arguments_MSGTYPE substrait_FunctionSignature_Argument
#define substrait_FunctionSignature_Aggregate_description_MSGTYPE substrait_FunctionSignature_Description
#define substrait_FunctionSignature_Aggregate_output_type_MSGTYPE substrait_DerivationExpression
#define substrait_FunctionSignature_Aggregate_final_variable_behavior_variadic_MSGTYPE substrait_FunctionSignature_FinalArgVariadic
#define substrait_FunctionSignature_Aggregate_final_variable_behavior_normal_MSGTYPE substrait_FunctionSignature_FinalArgNormal
#define substrait_FunctionSignature_Aggregate_intermediate_type_MSGTYPE substrait_Type
#define substrait_FunctionSignature_Aggregate_implementations_MSGTYPE substrait_FunctionSignature_Implementation

#define substrait_FunctionSignature_Window_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  arguments,         2) \
X(a, CALLBACK, REPEATED, STRING,   name,              3) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  description,       4) \
X(a, CALLBACK, SINGULAR, BOOL,     deterministic,     7) \
X(a, CALLBACK, SINGULAR, BOOL,     session_dependent,   8) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  intermediate_type,   9) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  output_type,      10) \
X(a, CALLBACK, SINGULAR, BOOL,     ordered,          11) \
X(a, CALLBACK, SINGULAR, UINT64,   max_set,          12) \
X(a, CALLBACK, SINGULAR, UENUM,    window_type,      14) \
X(a, CALLBACK, REPEATED, MESSAGE,  implementations,  15) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (final_variable_behavior,variadic,final_variable_behavior.variadic),  16) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (final_variable_behavior,normal,final_variable_behavior.normal),  17)
#define substrait_FunctionSignature_Window_CALLBACK pb_default_field_callback
#define substrait_FunctionSignature_Window_DEFAULT NULL
#define substrait_FunctionSignature_Window_arguments_MSGTYPE substrait_FunctionSignature_Argument
#define substrait_FunctionSignature_Window_description_MSGTYPE substrait_FunctionSignature_Description
#define substrait_FunctionSignature_Window_intermediate_type_MSGTYPE substrait_DerivationExpression
#define substrait_FunctionSignature_Window_output_type_MSGTYPE substrait_DerivationExpression
#define substrait_FunctionSignature_Window_implementations_MSGTYPE substrait_FunctionSignature_Implementation
#define substrait_FunctionSignature_Window_final_variable_behavior_variadic_MSGTYPE substrait_FunctionSignature_FinalArgVariadic
#define substrait_FunctionSignature_Window_final_variable_behavior_normal_MSGTYPE substrait_FunctionSignature_FinalArgNormal

#define substrait_FunctionSignature_Description_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   language,          1) \
X(a, CALLBACK, SINGULAR, STRING,   body,              2)
#define substrait_FunctionSignature_Description_CALLBACK pb_default_field_callback
#define substrait_FunctionSignature_Description_DEFAULT NULL

#define substrait_FunctionSignature_Implementation_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, UENUM,    type,              1) \
X(a, CALLBACK, SINGULAR, STRING,   uri,               2)
#define substrait_FunctionSignature_Implementation_CALLBACK pb_default_field_callback
#define substrait_FunctionSignature_Implementation_DEFAULT NULL

#define substrait_FunctionSignature_Argument_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (argument_kind,value,argument_kind.value),   2) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (argument_kind,type,argument_kind.type),   3) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (argument_kind,enum_,argument_kind.enum_),   4)
#define substrait_FunctionSignature_Argument_CALLBACK pb_default_field_callback
#define substrait_FunctionSignature_Argument_DEFAULT NULL
#define substrait_FunctionSignature_Argument_argument_kind_value_MSGTYPE substrait_FunctionSignature_Argument_ValueArgument
#define substrait_FunctionSignature_Argument_argument_kind_type_MSGTYPE substrait_FunctionSignature_Argument_TypeArgument
#define substrait_FunctionSignature_Argument_argument_kind_enum__MSGTYPE substrait_FunctionSignature_Argument_EnumArgument

#define substrait_FunctionSignature_Argument_ValueArgument_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  type,              1) \
X(a, CALLBACK, SINGULAR, BOOL,     constant,          2)
#define substrait_FunctionSignature_Argument_ValueArgument_CALLBACK pb_default_field_callback
#define substrait_FunctionSignature_Argument_ValueArgument_DEFAULT NULL
#define substrait_FunctionSignature_Argument_ValueArgument_type_MSGTYPE substrait_ParameterizedType

#define substrait_FunctionSignature_Argument_TypeArgument_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  type,              1)
#define substrait_FunctionSignature_Argument_TypeArgument_CALLBACK pb_default_field_callback
#define substrait_FunctionSignature_Argument_TypeArgument_DEFAULT NULL
#define substrait_FunctionSignature_Argument_TypeArgument_type_MSGTYPE substrait_ParameterizedType

#define substrait_FunctionSignature_Argument_EnumArgument_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   options,           1) \
X(a, CALLBACK, SINGULAR, BOOL,     optional,          2)
#define substrait_FunctionSignature_Argument_EnumArgument_CALLBACK pb_default_field_callback
#define substrait_FunctionSignature_Argument_EnumArgument_DEFAULT NULL

extern const pb_msgdesc_t substrait_FunctionSignature_msg;
extern const pb_msgdesc_t substrait_FunctionSignature_FinalArgVariadic_msg;
extern const pb_msgdesc_t substrait_FunctionSignature_FinalArgNormal_msg;
extern const pb_msgdesc_t substrait_FunctionSignature_Scalar_msg;
extern const pb_msgdesc_t substrait_FunctionSignature_Aggregate_msg;
extern const pb_msgdesc_t substrait_FunctionSignature_Window_msg;
extern const pb_msgdesc_t substrait_FunctionSignature_Description_msg;
extern const pb_msgdesc_t substrait_FunctionSignature_Implementation_msg;
extern const pb_msgdesc_t substrait_FunctionSignature_Argument_msg;
extern const pb_msgdesc_t substrait_FunctionSignature_Argument_ValueArgument_msg;
extern const pb_msgdesc_t substrait_FunctionSignature_Argument_TypeArgument_msg;
extern const pb_msgdesc_t substrait_FunctionSignature_Argument_EnumArgument_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define substrait_FunctionSignature_fields &substrait_FunctionSignature_msg
#define substrait_FunctionSignature_FinalArgVariadic_fields &substrait_FunctionSignature_FinalArgVariadic_msg
#define substrait_FunctionSignature_FinalArgNormal_fields &substrait_FunctionSignature_FinalArgNormal_msg
#define substrait_FunctionSignature_Scalar_fields &substrait_FunctionSignature_Scalar_msg
#define substrait_FunctionSignature_Aggregate_fields &substrait_FunctionSignature_Aggregate_msg
#define substrait_FunctionSignature_Window_fields &substrait_FunctionSignature_Window_msg
#define substrait_FunctionSignature_Description_fields &substrait_FunctionSignature_Description_msg
#define substrait_FunctionSignature_Implementation_fields &substrait_FunctionSignature_Implementation_msg
#define substrait_FunctionSignature_Argument_fields &substrait_FunctionSignature_Argument_msg
#define substrait_FunctionSignature_Argument_ValueArgument_fields &substrait_FunctionSignature_Argument_ValueArgument_msg
#define substrait_FunctionSignature_Argument_TypeArgument_fields &substrait_FunctionSignature_Argument_TypeArgument_msg
#define substrait_FunctionSignature_Argument_EnumArgument_fields &substrait_FunctionSignature_Argument_EnumArgument_msg

/* Maximum encoded size of messages (where known) */
/* substrait_FunctionSignature_FinalArgVariadic_size depends on runtime parameters */
/* substrait_FunctionSignature_Scalar_size depends on runtime parameters */
/* substrait_FunctionSignature_Aggregate_size depends on runtime parameters */
/* substrait_FunctionSignature_Window_size depends on runtime parameters */
/* substrait_FunctionSignature_Description_size depends on runtime parameters */
/* substrait_FunctionSignature_Implementation_size depends on runtime parameters */
/* substrait_FunctionSignature_Argument_size depends on runtime parameters */
/* substrait_FunctionSignature_Argument_ValueArgument_size depends on runtime parameters */
/* substrait_FunctionSignature_Argument_TypeArgument_size depends on runtime parameters */
/* substrait_FunctionSignature_Argument_EnumArgument_size depends on runtime parameters */
#define substrait_FunctionSignature_FinalArgNormal_size 0
#define substrait_FunctionSignature_size         0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
