/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_SUBSTRAIT_SUBSTRAIT_RELATIONS_PB_H_INCLUDED
#define PB_SUBSTRAIT_SUBSTRAIT_RELATIONS_PB_H_INCLUDED
#include <pb.h>
#include "substrait/any.pb.h"
#include "substrait/type.pb.h"
#include "substrait/expression.pb.h"
#include "substrait/extensions/extensions.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _substrait_ReadRel_LocalFiles_FileOrFiles_FileFormat { 
    substrait_ReadRel_LocalFiles_FileOrFiles_FileFormat_FILE_FORMAT_UNSPECIFIED = 0, 
    substrait_ReadRel_LocalFiles_FileOrFiles_FileFormat_FILE_FORMAT_PARQUET = 1 
} substrait_ReadRel_LocalFiles_FileOrFiles_FileFormat;

typedef enum _substrait_JoinRel_JoinType { 
    substrait_JoinRel_JoinType_JOIN_TYPE_UNSPECIFIED = 0, 
    substrait_JoinRel_JoinType_JOIN_TYPE_INNER = 1, 
    substrait_JoinRel_JoinType_JOIN_TYPE_OUTER = 2, 
    substrait_JoinRel_JoinType_JOIN_TYPE_LEFT = 3, 
    substrait_JoinRel_JoinType_JOIN_TYPE_RIGHT = 4, 
    substrait_JoinRel_JoinType_JOIN_TYPE_SEMI = 5, 
    substrait_JoinRel_JoinType_JOIN_TYPE_ANTI = 6 
} substrait_JoinRel_JoinType;

typedef enum _substrait_SetRel_SetOp { 
    substrait_SetRel_SetOp_SET_OP_UNSPECIFIED = 0, 
    substrait_SetRel_SetOp_SET_OP_MINUS_PRIMARY = 1, 
    substrait_SetRel_SetOp_SET_OP_MINUS_MULTISET = 2, 
    substrait_SetRel_SetOp_SET_OP_INTERSECTION_PRIMARY = 3, 
    substrait_SetRel_SetOp_SET_OP_INTERSECTION_MULTISET = 4, 
    substrait_SetRel_SetOp_SET_OP_UNION_DISTINCT = 5, 
    substrait_SetRel_SetOp_SET_OP_UNION_ALL = 6 
} substrait_SetRel_SetOp;

/* Struct definitions */
typedef struct _substrait_AggregateRel { 
    struct _substrait_RelCommon *common; 
    struct _substrait_Rel *input; 
    pb_size_t groupings_count;
    struct _substrait_AggregateRel_Grouping *groupings; 
    pb_size_t measures_count;
    struct _substrait_AggregateRel_Measure *measures; 
    struct _substrait_extensions_AdvancedExtension *advanced_extension; 
} substrait_AggregateRel;

typedef struct _substrait_AggregateRel_Grouping { 
    pb_size_t grouping_expressions_count;
    struct _substrait_Expression *grouping_expressions; 
} substrait_AggregateRel_Grouping;

typedef struct _substrait_AggregateRel_Measure { 
    struct _substrait_AggregateFunction *measure; 
    struct _substrait_Expression *filter; 
} substrait_AggregateRel_Measure;

typedef struct _substrait_ExtensionLeafRel { 
    struct _substrait_RelCommon *common; 
    struct _substrait_Any *detail; 
} substrait_ExtensionLeafRel;

typedef struct _substrait_ExtensionMultiRel { 
    struct _substrait_RelCommon *common; 
    pb_size_t inputs_count;
    struct _substrait_Rel *inputs; 
    struct _substrait_Any *detail; 
} substrait_ExtensionMultiRel;

typedef struct _substrait_ExtensionSingleRel { 
    struct _substrait_RelCommon *common; 
    struct _substrait_Rel *input; 
    struct _substrait_Any *detail; 
} substrait_ExtensionSingleRel;

typedef struct _substrait_FetchRel { 
    struct _substrait_RelCommon *common; 
    struct _substrait_Rel *input; 
    int64_t *offset; 
    int64_t *count; 
    struct _substrait_extensions_AdvancedExtension *advanced_extension; 
} substrait_FetchRel;

typedef struct _substrait_FilterRel { 
    struct _substrait_RelCommon *common; 
    struct _substrait_Rel *input; 
    struct _substrait_Expression *condition; 
    struct _substrait_extensions_AdvancedExtension *advanced_extension; 
} substrait_FilterRel;

typedef struct _substrait_JoinRel { 
    struct _substrait_RelCommon *common; 
    struct _substrait_Rel *left; 
    struct _substrait_Rel *right; 
    struct _substrait_Expression *expression; 
    struct _substrait_Expression *post_join_filter; 
    substrait_JoinRel_JoinType *type; 
    struct _substrait_extensions_AdvancedExtension *advanced_extension; 
} substrait_JoinRel;

/* A relation with output field names.

 This is for use at the root of a `Rel` tree. */
typedef struct _substrait_ProjectRel { 
    /* A relation */
    struct _substrait_RelCommon *common; 
    /* Field names in depth-first order */
    struct _substrait_Rel *input; 
    pb_size_t expressions_count;
    struct _substrait_Expression *expressions; 
    struct _substrait_extensions_AdvancedExtension *advanced_extension; 
} substrait_ProjectRel;

typedef struct _substrait_ReadRel { 
    struct _substrait_RelCommon *common; 
    struct _substrait_NamedStruct *base_schema; 
    struct _substrait_Expression *filter; 
    struct _substrait_Expression_MaskExpression *projection; 
    pb_size_t which_read_type;
    union {
        struct _substrait_ReadRel_VirtualTable *virtual_table;
        struct _substrait_ReadRel_LocalFiles *local_files;
        struct _substrait_ReadRel_NamedTable *named_table;
        struct _substrait_ReadRel_ExtensionTable *extension_table;
    } read_type; 
    struct _substrait_extensions_AdvancedExtension *advanced_extension; 
} substrait_ReadRel;

/* Stub to support extension with a single input */
typedef struct _substrait_ReadRel_ExtensionTable { 
    struct _substrait_Any *detail; 
} substrait_ReadRel_ExtensionTable;

/* Stub to support extension with a zero inputs */
typedef struct _substrait_ReadRel_LocalFiles { 
    pb_size_t items_count;
    struct _substrait_ReadRel_LocalFiles_FileOrFiles *items; 
    struct _substrait_extensions_AdvancedExtension *advanced_extension; 
} substrait_ReadRel_LocalFiles;

/* Stub to support extension with multiple inputs */
typedef struct _substrait_ReadRel_LocalFiles_FileOrFiles { 
    pb_size_t which_path_type;
    union {
        char *uri_path;
        char *uri_path_glob;
        char *uri_file;
        char *uri_folder;
    } path_type; 
    substrait_ReadRel_LocalFiles_FileOrFiles_FileFormat *format; 
    uint64_t *partition_index; 
    uint64_t *start; 
    uint64_t *length; 
} substrait_ReadRel_LocalFiles_FileOrFiles;

typedef struct _substrait_ReadRel_NamedTable { 
    pb_size_t names_count;
    char **names; 
    struct _substrait_extensions_AdvancedExtension *advanced_extension; 
} substrait_ReadRel_NamedTable;

typedef struct _substrait_ReadRel_VirtualTable { 
    pb_size_t values_count;
    struct _substrait_Expression_Literal_Struct *values; 
} substrait_ReadRel_VirtualTable;

typedef struct _substrait_Rel { 
    pb_size_t which_rel_type;
    union {
        struct _substrait_ReadRel *read;
        struct _substrait_FilterRel *filter;
        struct _substrait_FetchRel *fetch;
        struct _substrait_AggregateRel *aggregate;
        struct _substrait_SortRel *sort;
        struct _substrait_JoinRel *join;
        struct _substrait_ProjectRel *project;
        struct _substrait_SetRel *set;
        struct _substrait_ExtensionSingleRel *extension_single;
        struct _substrait_ExtensionMultiRel *extension_multi;
        struct _substrait_ExtensionLeafRel *extension_leaf;
    } rel_type; 
} substrait_Rel;

typedef struct _substrait_RelCommon { 
    pb_size_t which_emit_kind;
    union {
        struct _substrait_RelCommon_Direct *direct;
        struct _substrait_RelCommon_Emit *emit;
    } emit_kind; 
    struct _substrait_RelCommon_Hint *hint; 
    struct _substrait_extensions_AdvancedExtension *advanced_extension; 
} substrait_RelCommon;

typedef struct _substrait_RelCommon_Direct { 
    char dummy_field;
} substrait_RelCommon_Direct;

typedef struct _substrait_RelCommon_Emit { 
    pb_size_t output_mapping_count;
    int32_t *output_mapping; 
} substrait_RelCommon_Emit;

typedef struct _substrait_RelCommon_Hint { 
    struct _substrait_RelCommon_Hint_Stats *stats; 
    struct _substrait_RelCommon_Hint_RuntimeConstraint *constraint; 
    struct _substrait_extensions_AdvancedExtension *advanced_extension; 
} substrait_RelCommon_Hint;

typedef struct _substrait_RelCommon_Hint_RuntimeConstraint { 
    struct _substrait_extensions_AdvancedExtension *advanced_extension; 
} substrait_RelCommon_Hint_RuntimeConstraint;

typedef struct _substrait_RelCommon_Hint_Stats { 
    double *row_count; 
    double *record_size; 
    struct _substrait_extensions_AdvancedExtension *advanced_extension; 
} substrait_RelCommon_Hint_Stats;

typedef struct _substrait_RelRoot { 
    struct _substrait_Rel *input; 
    pb_size_t names_count;
    char **names; 
} substrait_RelRoot;

typedef struct _substrait_SetRel { 
    struct _substrait_RelCommon *common; 
    pb_size_t inputs_count;
    struct _substrait_Rel *inputs; 
    substrait_SetRel_SetOp *op; 
    struct _substrait_extensions_AdvancedExtension *advanced_extension; 
} substrait_SetRel;

typedef struct _substrait_SortRel { 
    struct _substrait_RelCommon *common; 
    struct _substrait_Rel *input; 
    pb_size_t sorts_count;
    struct _substrait_SortField *sorts; 
    struct _substrait_extensions_AdvancedExtension *advanced_extension; 
} substrait_SortRel;


/* Helper constants for enums */
#define _substrait_ReadRel_LocalFiles_FileOrFiles_FileFormat_MIN substrait_ReadRel_LocalFiles_FileOrFiles_FileFormat_FILE_FORMAT_UNSPECIFIED
#define _substrait_ReadRel_LocalFiles_FileOrFiles_FileFormat_MAX substrait_ReadRel_LocalFiles_FileOrFiles_FileFormat_FILE_FORMAT_PARQUET
#define _substrait_ReadRel_LocalFiles_FileOrFiles_FileFormat_ARRAYSIZE ((substrait_ReadRel_LocalFiles_FileOrFiles_FileFormat)(substrait_ReadRel_LocalFiles_FileOrFiles_FileFormat_FILE_FORMAT_PARQUET+1))

#define _substrait_JoinRel_JoinType_MIN substrait_JoinRel_JoinType_JOIN_TYPE_UNSPECIFIED
#define _substrait_JoinRel_JoinType_MAX substrait_JoinRel_JoinType_JOIN_TYPE_ANTI
#define _substrait_JoinRel_JoinType_ARRAYSIZE ((substrait_JoinRel_JoinType)(substrait_JoinRel_JoinType_JOIN_TYPE_ANTI+1))

#define _substrait_SetRel_SetOp_MIN substrait_SetRel_SetOp_SET_OP_UNSPECIFIED
#define _substrait_SetRel_SetOp_MAX substrait_SetRel_SetOp_SET_OP_UNION_ALL
#define _substrait_SetRel_SetOp_ARRAYSIZE ((substrait_SetRel_SetOp)(substrait_SetRel_SetOp_SET_OP_UNION_ALL+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define substrait_RelCommon_init_default         {0, {NULL}, NULL, NULL}
#define substrait_RelCommon_Direct_init_default  {0}
#define substrait_RelCommon_Emit_init_default    {0, NULL}
#define substrait_RelCommon_Hint_init_default    {NULL, NULL, NULL}
#define substrait_RelCommon_Hint_Stats_init_default {NULL, NULL, NULL}
#define substrait_RelCommon_Hint_RuntimeConstraint_init_default {NULL}
#define substrait_ReadRel_init_default           {NULL, NULL, NULL, NULL, 0, {NULL}, NULL}
#define substrait_ReadRel_NamedTable_init_default {0, NULL, NULL}
#define substrait_ReadRel_VirtualTable_init_default {0, NULL}
#define substrait_ReadRel_ExtensionTable_init_default {NULL}
#define substrait_ReadRel_LocalFiles_init_default {0, NULL, NULL}
#define substrait_ReadRel_LocalFiles_FileOrFiles_init_default {0, {NULL}, NULL, NULL, NULL, NULL}
#define substrait_ProjectRel_init_default        {NULL, NULL, 0, NULL, NULL}
#define substrait_JoinRel_init_default           {NULL, NULL, NULL, NULL, NULL, NULL, NULL}
#define substrait_FetchRel_init_default          {NULL, NULL, NULL, NULL, NULL}
#define substrait_AggregateRel_init_default      {NULL, NULL, 0, NULL, 0, NULL, NULL}
#define substrait_AggregateRel_Grouping_init_default {0, NULL}
#define substrait_AggregateRel_Measure_init_default {NULL, NULL}
#define substrait_SortRel_init_default           {NULL, NULL, 0, NULL, NULL}
#define substrait_FilterRel_init_default         {NULL, NULL, NULL, NULL}
#define substrait_SetRel_init_default            {NULL, 0, NULL, NULL, NULL}
#define substrait_ExtensionSingleRel_init_default {NULL, NULL, NULL}
#define substrait_ExtensionLeafRel_init_default  {NULL, NULL}
#define substrait_ExtensionMultiRel_init_default {NULL, 0, NULL, NULL}
#define substrait_RelRoot_init_default           {NULL, 0, NULL}
#define substrait_Rel_init_default               {0, {NULL}}
#define substrait_RelCommon_init_zero            {0, {NULL}, NULL, NULL}
#define substrait_RelCommon_Direct_init_zero     {0}
#define substrait_RelCommon_Emit_init_zero       {0, NULL}
#define substrait_RelCommon_Hint_init_zero       {NULL, NULL, NULL}
#define substrait_RelCommon_Hint_Stats_init_zero {NULL, NULL, NULL}
#define substrait_RelCommon_Hint_RuntimeConstraint_init_zero {NULL}
#define substrait_ReadRel_init_zero              {NULL, NULL, NULL, NULL, 0, {NULL}, NULL}
#define substrait_ReadRel_NamedTable_init_zero   {0, NULL, NULL}
#define substrait_ReadRel_VirtualTable_init_zero {0, NULL}
#define substrait_ReadRel_ExtensionTable_init_zero {NULL}
#define substrait_ReadRel_LocalFiles_init_zero   {0, NULL, NULL}
#define substrait_ReadRel_LocalFiles_FileOrFiles_init_zero {0, {NULL}, NULL, NULL, NULL, NULL}
#define substrait_ProjectRel_init_zero           {NULL, NULL, 0, NULL, NULL}
#define substrait_JoinRel_init_zero              {NULL, NULL, NULL, NULL, NULL, NULL, NULL}
#define substrait_FetchRel_init_zero             {NULL, NULL, NULL, NULL, NULL}
#define substrait_AggregateRel_init_zero         {NULL, NULL, 0, NULL, 0, NULL, NULL}
#define substrait_AggregateRel_Grouping_init_zero {0, NULL}
#define substrait_AggregateRel_Measure_init_zero {NULL, NULL}
#define substrait_SortRel_init_zero              {NULL, NULL, 0, NULL, NULL}
#define substrait_FilterRel_init_zero            {NULL, NULL, NULL, NULL}
#define substrait_SetRel_init_zero               {NULL, 0, NULL, NULL, NULL}
#define substrait_ExtensionSingleRel_init_zero   {NULL, NULL, NULL}
#define substrait_ExtensionLeafRel_init_zero     {NULL, NULL}
#define substrait_ExtensionMultiRel_init_zero    {NULL, 0, NULL, NULL}
#define substrait_RelRoot_init_zero              {NULL, 0, NULL}
#define substrait_Rel_init_zero                  {0, {NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define substrait_AggregateRel_common_tag        1
#define substrait_AggregateRel_input_tag         2
#define substrait_AggregateRel_groupings_tag     3
#define substrait_AggregateRel_measures_tag      4
#define substrait_AggregateRel_advanced_extension_tag 10
#define substrait_AggregateRel_Grouping_grouping_expressions_tag 1
#define substrait_AggregateRel_Measure_measure_tag 1
#define substrait_AggregateRel_Measure_filter_tag 2
#define substrait_ExtensionLeafRel_common_tag    1
#define substrait_ExtensionLeafRel_detail_tag    2
#define substrait_ExtensionMultiRel_common_tag   1
#define substrait_ExtensionMultiRel_inputs_tag   2
#define substrait_ExtensionMultiRel_detail_tag   3
#define substrait_ExtensionSingleRel_common_tag  1
#define substrait_ExtensionSingleRel_input_tag   2
#define substrait_ExtensionSingleRel_detail_tag  3
#define substrait_FetchRel_common_tag            1
#define substrait_FetchRel_input_tag             2
#define substrait_FetchRel_offset_tag            3
#define substrait_FetchRel_count_tag             4
#define substrait_FetchRel_advanced_extension_tag 10
#define substrait_FilterRel_common_tag           1
#define substrait_FilterRel_input_tag            2
#define substrait_FilterRel_condition_tag        3
#define substrait_FilterRel_advanced_extension_tag 10
#define substrait_JoinRel_common_tag             1
#define substrait_JoinRel_left_tag               2
#define substrait_JoinRel_right_tag              3
#define substrait_JoinRel_expression_tag         4
#define substrait_JoinRel_post_join_filter_tag   5
#define substrait_JoinRel_type_tag               6
#define substrait_JoinRel_advanced_extension_tag 10
#define substrait_ProjectRel_common_tag          1
#define substrait_ProjectRel_input_tag           2
#define substrait_ProjectRel_expressions_tag     3
#define substrait_ProjectRel_advanced_extension_tag 10
#define substrait_ReadRel_common_tag             1
#define substrait_ReadRel_base_schema_tag        2
#define substrait_ReadRel_filter_tag             3
#define substrait_ReadRel_projection_tag         4
#define substrait_ReadRel_virtual_table_tag      5
#define substrait_ReadRel_local_files_tag        6
#define substrait_ReadRel_named_table_tag        7
#define substrait_ReadRel_extension_table_tag    8
#define substrait_ReadRel_advanced_extension_tag 10
#define substrait_ReadRel_ExtensionTable_detail_tag 1
#define substrait_ReadRel_LocalFiles_items_tag   1
#define substrait_ReadRel_LocalFiles_advanced_extension_tag 10
#define substrait_ReadRel_LocalFiles_FileOrFiles_uri_path_tag 1
#define substrait_ReadRel_LocalFiles_FileOrFiles_uri_path_glob_tag 2
#define substrait_ReadRel_LocalFiles_FileOrFiles_uri_file_tag 3
#define substrait_ReadRel_LocalFiles_FileOrFiles_uri_folder_tag 4
#define substrait_ReadRel_LocalFiles_FileOrFiles_format_tag 5
#define substrait_ReadRel_LocalFiles_FileOrFiles_partition_index_tag 6
#define substrait_ReadRel_LocalFiles_FileOrFiles_start_tag 7
#define substrait_ReadRel_LocalFiles_FileOrFiles_length_tag 8
#define substrait_ReadRel_NamedTable_names_tag   1
#define substrait_ReadRel_NamedTable_advanced_extension_tag 10
#define substrait_ReadRel_VirtualTable_values_tag 1
#define substrait_Rel_read_tag                   1
#define substrait_Rel_filter_tag                 2
#define substrait_Rel_fetch_tag                  3
#define substrait_Rel_aggregate_tag              4
#define substrait_Rel_sort_tag                   5
#define substrait_Rel_join_tag                   6
#define substrait_Rel_project_tag                7
#define substrait_Rel_set_tag                    8
#define substrait_Rel_extension_single_tag       9
#define substrait_Rel_extension_multi_tag        10
#define substrait_Rel_extension_leaf_tag         11
#define substrait_RelCommon_direct_tag           1
#define substrait_RelCommon_emit_tag             2
#define substrait_RelCommon_hint_tag             3
#define substrait_RelCommon_advanced_extension_tag 4
#define substrait_RelCommon_Emit_output_mapping_tag 1
#define substrait_RelCommon_Hint_stats_tag       1
#define substrait_RelCommon_Hint_constraint_tag  2
#define substrait_RelCommon_Hint_advanced_extension_tag 10
#define substrait_RelCommon_Hint_RuntimeConstraint_advanced_extension_tag 10
#define substrait_RelCommon_Hint_Stats_row_count_tag 1
#define substrait_RelCommon_Hint_Stats_record_size_tag 2
#define substrait_RelCommon_Hint_Stats_advanced_extension_tag 10
#define substrait_RelRoot_input_tag              1
#define substrait_RelRoot_names_tag              2
#define substrait_SetRel_common_tag              1
#define substrait_SetRel_inputs_tag              2
#define substrait_SetRel_op_tag                  3
#define substrait_SetRel_advanced_extension_tag  10
#define substrait_SortRel_common_tag             1
#define substrait_SortRel_input_tag              2
#define substrait_SortRel_sorts_tag              3
#define substrait_SortRel_advanced_extension_tag 10

/* Struct field encoding specification for nanopb */
#define substrait_RelCommon_FIELDLIST(X, a) \
X(a, POINTER,  ONEOF,    MESSAGE,  (emit_kind,direct,emit_kind.direct),   1) \
X(a, POINTER,  ONEOF,    MESSAGE,  (emit_kind,emit,emit_kind.emit),   2) \
X(a, POINTER,  OPTIONAL, MESSAGE,  hint,              3) \
X(a, POINTER,  OPTIONAL, MESSAGE,  advanced_extension,   4)
#define substrait_RelCommon_CALLBACK NULL
#define substrait_RelCommon_DEFAULT NULL
#define substrait_RelCommon_emit_kind_direct_MSGTYPE substrait_RelCommon_Direct
#define substrait_RelCommon_emit_kind_emit_MSGTYPE substrait_RelCommon_Emit
#define substrait_RelCommon_hint_MSGTYPE substrait_RelCommon_Hint
#define substrait_RelCommon_advanced_extension_MSGTYPE substrait_extensions_AdvancedExtension

#define substrait_RelCommon_Direct_FIELDLIST(X, a) \

#define substrait_RelCommon_Direct_CALLBACK NULL
#define substrait_RelCommon_Direct_DEFAULT NULL

#define substrait_RelCommon_Emit_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, INT32,    output_mapping,    1)
#define substrait_RelCommon_Emit_CALLBACK NULL
#define substrait_RelCommon_Emit_DEFAULT NULL

#define substrait_RelCommon_Hint_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  stats,             1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  constraint,        2) \
X(a, POINTER,  OPTIONAL, MESSAGE,  advanced_extension,  10)
#define substrait_RelCommon_Hint_CALLBACK NULL
#define substrait_RelCommon_Hint_DEFAULT NULL
#define substrait_RelCommon_Hint_stats_MSGTYPE substrait_RelCommon_Hint_Stats
#define substrait_RelCommon_Hint_constraint_MSGTYPE substrait_RelCommon_Hint_RuntimeConstraint
#define substrait_RelCommon_Hint_advanced_extension_MSGTYPE substrait_extensions_AdvancedExtension

#define substrait_RelCommon_Hint_Stats_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, DOUBLE,   row_count,         1) \
X(a, POINTER,  SINGULAR, DOUBLE,   record_size,       2) \
X(a, POINTER,  OPTIONAL, MESSAGE,  advanced_extension,  10)
#define substrait_RelCommon_Hint_Stats_CALLBACK NULL
#define substrait_RelCommon_Hint_Stats_DEFAULT NULL
#define substrait_RelCommon_Hint_Stats_advanced_extension_MSGTYPE substrait_extensions_AdvancedExtension

#define substrait_RelCommon_Hint_RuntimeConstraint_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  advanced_extension,  10)
#define substrait_RelCommon_Hint_RuntimeConstraint_CALLBACK NULL
#define substrait_RelCommon_Hint_RuntimeConstraint_DEFAULT NULL
#define substrait_RelCommon_Hint_RuntimeConstraint_advanced_extension_MSGTYPE substrait_extensions_AdvancedExtension

#define substrait_ReadRel_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  common,            1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  base_schema,       2) \
X(a, POINTER,  OPTIONAL, MESSAGE,  filter,            3) \
X(a, POINTER,  OPTIONAL, MESSAGE,  projection,        4) \
X(a, POINTER,  ONEOF,    MESSAGE,  (read_type,virtual_table,read_type.virtual_table),   5) \
X(a, POINTER,  ONEOF,    MESSAGE,  (read_type,local_files,read_type.local_files),   6) \
X(a, POINTER,  ONEOF,    MESSAGE,  (read_type,named_table,read_type.named_table),   7) \
X(a, POINTER,  ONEOF,    MESSAGE,  (read_type,extension_table,read_type.extension_table),   8) \
X(a, POINTER,  OPTIONAL, MESSAGE,  advanced_extension,  10)
#define substrait_ReadRel_CALLBACK NULL
#define substrait_ReadRel_DEFAULT NULL
#define substrait_ReadRel_common_MSGTYPE substrait_RelCommon
#define substrait_ReadRel_base_schema_MSGTYPE substrait_NamedStruct
#define substrait_ReadRel_filter_MSGTYPE substrait_Expression
#define substrait_ReadRel_projection_MSGTYPE substrait_Expression_MaskExpression
#define substrait_ReadRel_read_type_virtual_table_MSGTYPE substrait_ReadRel_VirtualTable
#define substrait_ReadRel_read_type_local_files_MSGTYPE substrait_ReadRel_LocalFiles
#define substrait_ReadRel_read_type_named_table_MSGTYPE substrait_ReadRel_NamedTable
#define substrait_ReadRel_read_type_extension_table_MSGTYPE substrait_ReadRel_ExtensionTable
#define substrait_ReadRel_advanced_extension_MSGTYPE substrait_extensions_AdvancedExtension

#define substrait_ReadRel_NamedTable_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, STRING,   names,             1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  advanced_extension,  10)
#define substrait_ReadRel_NamedTable_CALLBACK NULL
#define substrait_ReadRel_NamedTable_DEFAULT NULL
#define substrait_ReadRel_NamedTable_advanced_extension_MSGTYPE substrait_extensions_AdvancedExtension

#define substrait_ReadRel_VirtualTable_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  values,            1)
#define substrait_ReadRel_VirtualTable_CALLBACK NULL
#define substrait_ReadRel_VirtualTable_DEFAULT NULL
#define substrait_ReadRel_VirtualTable_values_MSGTYPE substrait_Expression_Literal_Struct

#define substrait_ReadRel_ExtensionTable_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  detail,            1)
#define substrait_ReadRel_ExtensionTable_CALLBACK NULL
#define substrait_ReadRel_ExtensionTable_DEFAULT NULL
#define substrait_ReadRel_ExtensionTable_detail_MSGTYPE substrait_Any

#define substrait_ReadRel_LocalFiles_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  items,             1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  advanced_extension,  10)
#define substrait_ReadRel_LocalFiles_CALLBACK NULL
#define substrait_ReadRel_LocalFiles_DEFAULT NULL
#define substrait_ReadRel_LocalFiles_items_MSGTYPE substrait_ReadRel_LocalFiles_FileOrFiles
#define substrait_ReadRel_LocalFiles_advanced_extension_MSGTYPE substrait_extensions_AdvancedExtension

#define substrait_ReadRel_LocalFiles_FileOrFiles_FIELDLIST(X, a) \
X(a, POINTER,  ONEOF,    STRING,   (path_type,uri_path,path_type.uri_path),   1) \
X(a, POINTER,  ONEOF,    STRING,   (path_type,uri_path_glob,path_type.uri_path_glob),   2) \
X(a, POINTER,  ONEOF,    STRING,   (path_type,uri_file,path_type.uri_file),   3) \
X(a, POINTER,  ONEOF,    STRING,   (path_type,uri_folder,path_type.uri_folder),   4) \
X(a, POINTER,  SINGULAR, UENUM,    format,            5) \
X(a, POINTER,  SINGULAR, UINT64,   partition_index,   6) \
X(a, POINTER,  SINGULAR, UINT64,   start,             7) \
X(a, POINTER,  SINGULAR, UINT64,   length,            8)
#define substrait_ReadRel_LocalFiles_FileOrFiles_CALLBACK NULL
#define substrait_ReadRel_LocalFiles_FileOrFiles_DEFAULT NULL

#define substrait_ProjectRel_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  common,            1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  input,             2) \
X(a, POINTER,  REPEATED, MESSAGE,  expressions,       3) \
X(a, POINTER,  OPTIONAL, MESSAGE,  advanced_extension,  10)
#define substrait_ProjectRel_CALLBACK NULL
#define substrait_ProjectRel_DEFAULT NULL
#define substrait_ProjectRel_common_MSGTYPE substrait_RelCommon
#define substrait_ProjectRel_input_MSGTYPE substrait_Rel
#define substrait_ProjectRel_expressions_MSGTYPE substrait_Expression
#define substrait_ProjectRel_advanced_extension_MSGTYPE substrait_extensions_AdvancedExtension

#define substrait_JoinRel_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  common,            1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  left,              2) \
X(a, POINTER,  OPTIONAL, MESSAGE,  right,             3) \
X(a, POINTER,  OPTIONAL, MESSAGE,  expression,        4) \
X(a, POINTER,  OPTIONAL, MESSAGE,  post_join_filter,   5) \
X(a, POINTER,  SINGULAR, UENUM,    type,              6) \
X(a, POINTER,  OPTIONAL, MESSAGE,  advanced_extension,  10)
#define substrait_JoinRel_CALLBACK NULL
#define substrait_JoinRel_DEFAULT NULL
#define substrait_JoinRel_common_MSGTYPE substrait_RelCommon
#define substrait_JoinRel_left_MSGTYPE substrait_Rel
#define substrait_JoinRel_right_MSGTYPE substrait_Rel
#define substrait_JoinRel_expression_MSGTYPE substrait_Expression
#define substrait_JoinRel_post_join_filter_MSGTYPE substrait_Expression
#define substrait_JoinRel_advanced_extension_MSGTYPE substrait_extensions_AdvancedExtension

#define substrait_FetchRel_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  common,            1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  input,             2) \
X(a, POINTER,  SINGULAR, INT64,    offset,            3) \
X(a, POINTER,  SINGULAR, INT64,    count,             4) \
X(a, POINTER,  OPTIONAL, MESSAGE,  advanced_extension,  10)
#define substrait_FetchRel_CALLBACK NULL
#define substrait_FetchRel_DEFAULT NULL
#define substrait_FetchRel_common_MSGTYPE substrait_RelCommon
#define substrait_FetchRel_input_MSGTYPE substrait_Rel
#define substrait_FetchRel_advanced_extension_MSGTYPE substrait_extensions_AdvancedExtension

#define substrait_AggregateRel_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  common,            1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  input,             2) \
X(a, POINTER,  REPEATED, MESSAGE,  groupings,         3) \
X(a, POINTER,  REPEATED, MESSAGE,  measures,          4) \
X(a, POINTER,  OPTIONAL, MESSAGE,  advanced_extension,  10)
#define substrait_AggregateRel_CALLBACK NULL
#define substrait_AggregateRel_DEFAULT NULL
#define substrait_AggregateRel_common_MSGTYPE substrait_RelCommon
#define substrait_AggregateRel_input_MSGTYPE substrait_Rel
#define substrait_AggregateRel_groupings_MSGTYPE substrait_AggregateRel_Grouping
#define substrait_AggregateRel_measures_MSGTYPE substrait_AggregateRel_Measure
#define substrait_AggregateRel_advanced_extension_MSGTYPE substrait_extensions_AdvancedExtension

#define substrait_AggregateRel_Grouping_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  grouping_expressions,   1)
#define substrait_AggregateRel_Grouping_CALLBACK NULL
#define substrait_AggregateRel_Grouping_DEFAULT NULL
#define substrait_AggregateRel_Grouping_grouping_expressions_MSGTYPE substrait_Expression

#define substrait_AggregateRel_Measure_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  measure,           1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  filter,            2)
#define substrait_AggregateRel_Measure_CALLBACK NULL
#define substrait_AggregateRel_Measure_DEFAULT NULL
#define substrait_AggregateRel_Measure_measure_MSGTYPE substrait_AggregateFunction
#define substrait_AggregateRel_Measure_filter_MSGTYPE substrait_Expression

#define substrait_SortRel_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  common,            1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  input,             2) \
X(a, POINTER,  REPEATED, MESSAGE,  sorts,             3) \
X(a, POINTER,  OPTIONAL, MESSAGE,  advanced_extension,  10)
#define substrait_SortRel_CALLBACK NULL
#define substrait_SortRel_DEFAULT NULL
#define substrait_SortRel_common_MSGTYPE substrait_RelCommon
#define substrait_SortRel_input_MSGTYPE substrait_Rel
#define substrait_SortRel_sorts_MSGTYPE substrait_SortField
#define substrait_SortRel_advanced_extension_MSGTYPE substrait_extensions_AdvancedExtension

#define substrait_FilterRel_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  common,            1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  input,             2) \
X(a, POINTER,  OPTIONAL, MESSAGE,  condition,         3) \
X(a, POINTER,  OPTIONAL, MESSAGE,  advanced_extension,  10)
#define substrait_FilterRel_CALLBACK NULL
#define substrait_FilterRel_DEFAULT NULL
#define substrait_FilterRel_common_MSGTYPE substrait_RelCommon
#define substrait_FilterRel_input_MSGTYPE substrait_Rel
#define substrait_FilterRel_condition_MSGTYPE substrait_Expression
#define substrait_FilterRel_advanced_extension_MSGTYPE substrait_extensions_AdvancedExtension

#define substrait_SetRel_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  common,            1) \
X(a, POINTER,  REPEATED, MESSAGE,  inputs,            2) \
X(a, POINTER,  SINGULAR, UENUM,    op,                3) \
X(a, POINTER,  OPTIONAL, MESSAGE,  advanced_extension,  10)
#define substrait_SetRel_CALLBACK NULL
#define substrait_SetRel_DEFAULT NULL
#define substrait_SetRel_common_MSGTYPE substrait_RelCommon
#define substrait_SetRel_inputs_MSGTYPE substrait_Rel
#define substrait_SetRel_advanced_extension_MSGTYPE substrait_extensions_AdvancedExtension

#define substrait_ExtensionSingleRel_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  common,            1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  input,             2) \
X(a, POINTER,  OPTIONAL, MESSAGE,  detail,            3)
#define substrait_ExtensionSingleRel_CALLBACK NULL
#define substrait_ExtensionSingleRel_DEFAULT NULL
#define substrait_ExtensionSingleRel_common_MSGTYPE substrait_RelCommon
#define substrait_ExtensionSingleRel_input_MSGTYPE substrait_Rel
#define substrait_ExtensionSingleRel_detail_MSGTYPE substrait_Any

#define substrait_ExtensionLeafRel_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  common,            1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  detail,            2)
#define substrait_ExtensionLeafRel_CALLBACK NULL
#define substrait_ExtensionLeafRel_DEFAULT NULL
#define substrait_ExtensionLeafRel_common_MSGTYPE substrait_RelCommon
#define substrait_ExtensionLeafRel_detail_MSGTYPE substrait_Any

#define substrait_ExtensionMultiRel_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  common,            1) \
X(a, POINTER,  REPEATED, MESSAGE,  inputs,            2) \
X(a, POINTER,  OPTIONAL, MESSAGE,  detail,            3)
#define substrait_ExtensionMultiRel_CALLBACK NULL
#define substrait_ExtensionMultiRel_DEFAULT NULL
#define substrait_ExtensionMultiRel_common_MSGTYPE substrait_RelCommon
#define substrait_ExtensionMultiRel_inputs_MSGTYPE substrait_Rel
#define substrait_ExtensionMultiRel_detail_MSGTYPE substrait_Any

#define substrait_RelRoot_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  input,             1) \
X(a, POINTER,  REPEATED, STRING,   names,             2)
#define substrait_RelRoot_CALLBACK NULL
#define substrait_RelRoot_DEFAULT NULL
#define substrait_RelRoot_input_MSGTYPE substrait_Rel

#define substrait_Rel_FIELDLIST(X, a) \
X(a, POINTER,  ONEOF,    MESSAGE,  (rel_type,read,rel_type.read),   1) \
X(a, POINTER,  ONEOF,    MESSAGE,  (rel_type,filter,rel_type.filter),   2) \
X(a, POINTER,  ONEOF,    MESSAGE,  (rel_type,fetch,rel_type.fetch),   3) \
X(a, POINTER,  ONEOF,    MESSAGE,  (rel_type,aggregate,rel_type.aggregate),   4) \
X(a, POINTER,  ONEOF,    MESSAGE,  (rel_type,sort,rel_type.sort),   5) \
X(a, POINTER,  ONEOF,    MESSAGE,  (rel_type,join,rel_type.join),   6) \
X(a, POINTER,  ONEOF,    MESSAGE,  (rel_type,project,rel_type.project),   7) \
X(a, POINTER,  ONEOF,    MESSAGE,  (rel_type,set,rel_type.set),   8) \
X(a, POINTER,  ONEOF,    MESSAGE,  (rel_type,extension_single,rel_type.extension_single),   9) \
X(a, POINTER,  ONEOF,    MESSAGE,  (rel_type,extension_multi,rel_type.extension_multi),  10) \
X(a, POINTER,  ONEOF,    MESSAGE,  (rel_type,extension_leaf,rel_type.extension_leaf),  11)
#define substrait_Rel_CALLBACK NULL
#define substrait_Rel_DEFAULT NULL
#define substrait_Rel_rel_type_read_MSGTYPE substrait_ReadRel
#define substrait_Rel_rel_type_filter_MSGTYPE substrait_FilterRel
#define substrait_Rel_rel_type_fetch_MSGTYPE substrait_FetchRel
#define substrait_Rel_rel_type_aggregate_MSGTYPE substrait_AggregateRel
#define substrait_Rel_rel_type_sort_MSGTYPE substrait_SortRel
#define substrait_Rel_rel_type_join_MSGTYPE substrait_JoinRel
#define substrait_Rel_rel_type_project_MSGTYPE substrait_ProjectRel
#define substrait_Rel_rel_type_set_MSGTYPE substrait_SetRel
#define substrait_Rel_rel_type_extension_single_MSGTYPE substrait_ExtensionSingleRel
#define substrait_Rel_rel_type_extension_multi_MSGTYPE substrait_ExtensionMultiRel
#define substrait_Rel_rel_type_extension_leaf_MSGTYPE substrait_ExtensionLeafRel

extern const pb_msgdesc_t substrait_RelCommon_msg;
extern const pb_msgdesc_t substrait_RelCommon_Direct_msg;
extern const pb_msgdesc_t substrait_RelCommon_Emit_msg;
extern const pb_msgdesc_t substrait_RelCommon_Hint_msg;
extern const pb_msgdesc_t substrait_RelCommon_Hint_Stats_msg;
extern const pb_msgdesc_t substrait_RelCommon_Hint_RuntimeConstraint_msg;
extern const pb_msgdesc_t substrait_ReadRel_msg;
extern const pb_msgdesc_t substrait_ReadRel_NamedTable_msg;
extern const pb_msgdesc_t substrait_ReadRel_VirtualTable_msg;
extern const pb_msgdesc_t substrait_ReadRel_ExtensionTable_msg;
extern const pb_msgdesc_t substrait_ReadRel_LocalFiles_msg;
extern const pb_msgdesc_t substrait_ReadRel_LocalFiles_FileOrFiles_msg;
extern const pb_msgdesc_t substrait_ProjectRel_msg;
extern const pb_msgdesc_t substrait_JoinRel_msg;
extern const pb_msgdesc_t substrait_FetchRel_msg;
extern const pb_msgdesc_t substrait_AggregateRel_msg;
extern const pb_msgdesc_t substrait_AggregateRel_Grouping_msg;
extern const pb_msgdesc_t substrait_AggregateRel_Measure_msg;
extern const pb_msgdesc_t substrait_SortRel_msg;
extern const pb_msgdesc_t substrait_FilterRel_msg;
extern const pb_msgdesc_t substrait_SetRel_msg;
extern const pb_msgdesc_t substrait_ExtensionSingleRel_msg;
extern const pb_msgdesc_t substrait_ExtensionLeafRel_msg;
extern const pb_msgdesc_t substrait_ExtensionMultiRel_msg;
extern const pb_msgdesc_t substrait_RelRoot_msg;
extern const pb_msgdesc_t substrait_Rel_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define substrait_RelCommon_fields &substrait_RelCommon_msg
#define substrait_RelCommon_Direct_fields &substrait_RelCommon_Direct_msg
#define substrait_RelCommon_Emit_fields &substrait_RelCommon_Emit_msg
#define substrait_RelCommon_Hint_fields &substrait_RelCommon_Hint_msg
#define substrait_RelCommon_Hint_Stats_fields &substrait_RelCommon_Hint_Stats_msg
#define substrait_RelCommon_Hint_RuntimeConstraint_fields &substrait_RelCommon_Hint_RuntimeConstraint_msg
#define substrait_ReadRel_fields &substrait_ReadRel_msg
#define substrait_ReadRel_NamedTable_fields &substrait_ReadRel_NamedTable_msg
#define substrait_ReadRel_VirtualTable_fields &substrait_ReadRel_VirtualTable_msg
#define substrait_ReadRel_ExtensionTable_fields &substrait_ReadRel_ExtensionTable_msg
#define substrait_ReadRel_LocalFiles_fields &substrait_ReadRel_LocalFiles_msg
#define substrait_ReadRel_LocalFiles_FileOrFiles_fields &substrait_ReadRel_LocalFiles_FileOrFiles_msg
#define substrait_ProjectRel_fields &substrait_ProjectRel_msg
#define substrait_JoinRel_fields &substrait_JoinRel_msg
#define substrait_FetchRel_fields &substrait_FetchRel_msg
#define substrait_AggregateRel_fields &substrait_AggregateRel_msg
#define substrait_AggregateRel_Grouping_fields &substrait_AggregateRel_Grouping_msg
#define substrait_AggregateRel_Measure_fields &substrait_AggregateRel_Measure_msg
#define substrait_SortRel_fields &substrait_SortRel_msg
#define substrait_FilterRel_fields &substrait_FilterRel_msg
#define substrait_SetRel_fields &substrait_SetRel_msg
#define substrait_ExtensionSingleRel_fields &substrait_ExtensionSingleRel_msg
#define substrait_ExtensionLeafRel_fields &substrait_ExtensionLeafRel_msg
#define substrait_ExtensionMultiRel_fields &substrait_ExtensionMultiRel_msg
#define substrait_RelRoot_fields &substrait_RelRoot_msg
#define substrait_Rel_fields &substrait_Rel_msg

/* Maximum encoded size of messages (where known) */
/* substrait_RelCommon_size depends on runtime parameters */
/* substrait_RelCommon_Emit_size depends on runtime parameters */
/* substrait_RelCommon_Hint_size depends on runtime parameters */
/* substrait_RelCommon_Hint_Stats_size depends on runtime parameters */
/* substrait_RelCommon_Hint_RuntimeConstraint_size depends on runtime parameters */
/* substrait_ReadRel_size depends on runtime parameters */
/* substrait_ReadRel_NamedTable_size depends on runtime parameters */
/* substrait_ReadRel_VirtualTable_size depends on runtime parameters */
/* substrait_ReadRel_ExtensionTable_size depends on runtime parameters */
/* substrait_ReadRel_LocalFiles_size depends on runtime parameters */
/* substrait_ReadRel_LocalFiles_FileOrFiles_size depends on runtime parameters */
/* substrait_ProjectRel_size depends on runtime parameters */
/* substrait_JoinRel_size depends on runtime parameters */
/* substrait_FetchRel_size depends on runtime parameters */
/* substrait_AggregateRel_size depends on runtime parameters */
/* substrait_AggregateRel_Grouping_size depends on runtime parameters */
/* substrait_AggregateRel_Measure_size depends on runtime parameters */
/* substrait_SortRel_size depends on runtime parameters */
/* substrait_FilterRel_size depends on runtime parameters */
/* substrait_SetRel_size depends on runtime parameters */
/* substrait_ExtensionSingleRel_size depends on runtime parameters */
/* substrait_ExtensionLeafRel_size depends on runtime parameters */
/* substrait_ExtensionMultiRel_size depends on runtime parameters */
/* substrait_RelRoot_size depends on runtime parameters */
/* substrait_Rel_size depends on runtime parameters */
#define substrait_RelCommon_Direct_size          0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
