/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_SUBSTRAIT_SUBSTRAIT_TYPE_PB_H_INCLUDED
#define PB_SUBSTRAIT_SUBSTRAIT_TYPE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _substrait_Type_Nullability { 
    substrait_Type_Nullability_NULLABILITY_UNSPECIFIED = 0, 
    substrait_Type_Nullability_NULLABILITY_NULLABLE = 1, 
    substrait_Type_Nullability_NULLABILITY_REQUIRED = 2 
} substrait_Type_Nullability;

/* Struct definitions */
typedef struct _substrait_NamedStruct { 
    pb_callback_t names; 
    pb_callback_t struct_; 
} substrait_NamedStruct;

typedef struct _substrait_Type { 
    pb_size_t which_kind;
    union {
        pb_callback_t bool_;
        pb_callback_t i8;
        pb_callback_t i16;
        pb_callback_t i32;
        pb_callback_t i64;
        pb_callback_t fp32;
        pb_callback_t fp64;
        pb_callback_t string;
        pb_callback_t binary;
        pb_callback_t timestamp;
        pb_callback_t date;
        pb_callback_t time;
        pb_callback_t interval_year;
        pb_callback_t interval_day;
        pb_callback_t fixed_char;
        pb_callback_t varchar;
        pb_callback_t fixed_binary;
        pb_callback_t decimal;
        pb_callback_t struct_;
        pb_callback_t list;
        pb_callback_t map;
        pb_callback_t timestamp_tz;
        pb_callback_t user_defined_type_reference;
        pb_callback_t uuid;
    } kind; 
} substrait_Type;

typedef struct _substrait_Type_Binary { 
    pb_callback_t type_variation_reference; 
    pb_callback_t nullability; 
} substrait_Type_Binary;

/* A message for modeling name/type pairs.

 Useful for representing relation schemas.

 Notes:

 * The names field is in depth-first order.

 For example a schema such as:

 a: int64
 b: struct<c: float32, d: string>

 would have a `names` field that looks like:

 ["a", "b", "c", "d"]

 * Only struct fields are contained in this field's elements,
 * Map keys should be traversed first, then values when producing/consuming */
typedef struct _substrait_Type_Boolean { 
    /* list of names in dfs order */
    pb_callback_t type_variation_reference; 
    pb_callback_t nullability; 
} substrait_Type_Boolean;

typedef struct _substrait_Type_Date { 
    pb_callback_t type_variation_reference; 
    pb_callback_t nullability; 
} substrait_Type_Date;

typedef struct _substrait_Type_Decimal { 
    pb_callback_t scale; 
    pb_callback_t precision; 
    pb_callback_t type_variation_reference; 
    pb_callback_t nullability; 
} substrait_Type_Decimal;

typedef struct _substrait_Type_FP32 { 
    pb_callback_t type_variation_reference; 
    pb_callback_t nullability; 
} substrait_Type_FP32;

typedef struct _substrait_Type_FP64 { 
    pb_callback_t type_variation_reference; 
    pb_callback_t nullability; 
} substrait_Type_FP64;

typedef struct _substrait_Type_FixedBinary { 
    pb_callback_t length; 
    pb_callback_t type_variation_reference; 
    pb_callback_t nullability; 
} substrait_Type_FixedBinary;

typedef struct _substrait_Type_FixedChar { 
    pb_callback_t length; 
    pb_callback_t type_variation_reference; 
    pb_callback_t nullability; 
} substrait_Type_FixedChar;

typedef struct _substrait_Type_I16 { 
    pb_callback_t type_variation_reference; 
    pb_callback_t nullability; 
} substrait_Type_I16;

typedef struct _substrait_Type_I32 { 
    pb_callback_t type_variation_reference; 
    pb_callback_t nullability; 
} substrait_Type_I32;

typedef struct _substrait_Type_I64 { 
    pb_callback_t type_variation_reference; 
    pb_callback_t nullability; 
} substrait_Type_I64;

typedef struct _substrait_Type_I8 { 
    pb_callback_t type_variation_reference; 
    pb_callback_t nullability; 
} substrait_Type_I8;

typedef struct _substrait_Type_IntervalDay { 
    pb_callback_t type_variation_reference; 
    pb_callback_t nullability; 
} substrait_Type_IntervalDay;

typedef struct _substrait_Type_IntervalYear { 
    pb_callback_t type_variation_reference; 
    pb_callback_t nullability; 
} substrait_Type_IntervalYear;

typedef struct _substrait_Type_List { 
    pb_callback_t type; 
    pb_callback_t type_variation_reference; 
    pb_callback_t nullability; 
} substrait_Type_List;

typedef struct _substrait_Type_Map { 
    pb_callback_t key; 
    pb_callback_t value; 
    pb_callback_t type_variation_reference; 
    pb_callback_t nullability; 
} substrait_Type_Map;

typedef struct _substrait_Type_String { 
    pb_callback_t type_variation_reference; 
    pb_callback_t nullability; 
} substrait_Type_String;

typedef struct _substrait_Type_Struct { 
    pb_callback_t types; 
    pb_callback_t type_variation_reference; 
    pb_callback_t nullability; 
} substrait_Type_Struct;

typedef struct _substrait_Type_Time { 
    pb_callback_t type_variation_reference; 
    pb_callback_t nullability; 
} substrait_Type_Time;

typedef struct _substrait_Type_Timestamp { 
    pb_callback_t type_variation_reference; 
    pb_callback_t nullability; 
} substrait_Type_Timestamp;

typedef struct _substrait_Type_TimestampTZ { 
    pb_callback_t type_variation_reference; 
    pb_callback_t nullability; 
} substrait_Type_TimestampTZ;

typedef struct _substrait_Type_UUID { 
    pb_callback_t type_variation_reference; 
    pb_callback_t nullability; 
} substrait_Type_UUID;

typedef struct _substrait_Type_VarChar { 
    pb_callback_t length; 
    pb_callback_t type_variation_reference; 
    pb_callback_t nullability; 
} substrait_Type_VarChar;


/* Helper constants for enums */
#define _substrait_Type_Nullability_MIN substrait_Type_Nullability_NULLABILITY_UNSPECIFIED
#define _substrait_Type_Nullability_MAX substrait_Type_Nullability_NULLABILITY_REQUIRED
#define _substrait_Type_Nullability_ARRAYSIZE ((substrait_Type_Nullability)(substrait_Type_Nullability_NULLABILITY_REQUIRED+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define substrait_Type_init_default              {0, {{{NULL}, NULL}}}
#define substrait_Type_Boolean_init_default      {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_I8_init_default           {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_I16_init_default          {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_I32_init_default          {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_I64_init_default          {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_FP32_init_default         {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_FP64_init_default         {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_String_init_default       {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_Binary_init_default       {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_Timestamp_init_default    {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_Date_init_default         {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_Time_init_default         {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_TimestampTZ_init_default  {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_IntervalYear_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_IntervalDay_init_default  {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_UUID_init_default         {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_FixedChar_init_default    {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_VarChar_init_default      {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_FixedBinary_init_default  {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_Decimal_init_default      {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_Struct_init_default       {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_List_init_default         {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_Map_init_default          {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_NamedStruct_init_default       {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_init_zero                 {0, {{{NULL}, NULL}}}
#define substrait_Type_Boolean_init_zero         {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_I8_init_zero              {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_I16_init_zero             {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_I32_init_zero             {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_I64_init_zero             {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_FP32_init_zero            {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_FP64_init_zero            {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_String_init_zero          {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_Binary_init_zero          {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_Timestamp_init_zero       {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_Date_init_zero            {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_Time_init_zero            {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_TimestampTZ_init_zero     {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_IntervalYear_init_zero    {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_IntervalDay_init_zero     {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_UUID_init_zero            {{{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_FixedChar_init_zero       {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_VarChar_init_zero         {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_FixedBinary_init_zero     {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_Decimal_init_zero         {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_Struct_init_zero          {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_List_init_zero            {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_Type_Map_init_zero             {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define substrait_NamedStruct_init_zero          {{{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define substrait_NamedStruct_names_tag          1
#define substrait_NamedStruct_struct__tag        2
#define substrait_Type_bool__tag                 1
#define substrait_Type_i8_tag                    2
#define substrait_Type_i16_tag                   3
#define substrait_Type_i32_tag                   5
#define substrait_Type_i64_tag                   7
#define substrait_Type_fp32_tag                  10
#define substrait_Type_fp64_tag                  11
#define substrait_Type_string_tag                12
#define substrait_Type_binary_tag                13
#define substrait_Type_timestamp_tag             14
#define substrait_Type_date_tag                  16
#define substrait_Type_time_tag                  17
#define substrait_Type_interval_year_tag         19
#define substrait_Type_interval_day_tag          20
#define substrait_Type_fixed_char_tag            21
#define substrait_Type_varchar_tag               22
#define substrait_Type_fixed_binary_tag          23
#define substrait_Type_decimal_tag               24
#define substrait_Type_struct__tag               25
#define substrait_Type_list_tag                  27
#define substrait_Type_map_tag                   28
#define substrait_Type_timestamp_tz_tag          29
#define substrait_Type_user_defined_type_reference_tag 31
#define substrait_Type_uuid_tag                  32
#define substrait_Type_Binary_type_variation_reference_tag 1
#define substrait_Type_Binary_nullability_tag    2
#define substrait_Type_Boolean_type_variation_reference_tag 1
#define substrait_Type_Boolean_nullability_tag   2
#define substrait_Type_Date_type_variation_reference_tag 1
#define substrait_Type_Date_nullability_tag      2
#define substrait_Type_Decimal_scale_tag         1
#define substrait_Type_Decimal_precision_tag     2
#define substrait_Type_Decimal_type_variation_reference_tag 3
#define substrait_Type_Decimal_nullability_tag   4
#define substrait_Type_FP32_type_variation_reference_tag 1
#define substrait_Type_FP32_nullability_tag      2
#define substrait_Type_FP64_type_variation_reference_tag 1
#define substrait_Type_FP64_nullability_tag      2
#define substrait_Type_FixedBinary_length_tag    1
#define substrait_Type_FixedBinary_type_variation_reference_tag 2
#define substrait_Type_FixedBinary_nullability_tag 3
#define substrait_Type_FixedChar_length_tag      1
#define substrait_Type_FixedChar_type_variation_reference_tag 2
#define substrait_Type_FixedChar_nullability_tag 3
#define substrait_Type_I16_type_variation_reference_tag 1
#define substrait_Type_I16_nullability_tag       2
#define substrait_Type_I32_type_variation_reference_tag 1
#define substrait_Type_I32_nullability_tag       2
#define substrait_Type_I64_type_variation_reference_tag 1
#define substrait_Type_I64_nullability_tag       2
#define substrait_Type_I8_type_variation_reference_tag 1
#define substrait_Type_I8_nullability_tag        2
#define substrait_Type_IntervalDay_type_variation_reference_tag 1
#define substrait_Type_IntervalDay_nullability_tag 2
#define substrait_Type_IntervalYear_type_variation_reference_tag 1
#define substrait_Type_IntervalYear_nullability_tag 2
#define substrait_Type_List_type_tag             1
#define substrait_Type_List_type_variation_reference_tag 2
#define substrait_Type_List_nullability_tag      3
#define substrait_Type_Map_key_tag               1
#define substrait_Type_Map_value_tag             2
#define substrait_Type_Map_type_variation_reference_tag 3
#define substrait_Type_Map_nullability_tag       4
#define substrait_Type_String_type_variation_reference_tag 1
#define substrait_Type_String_nullability_tag    2
#define substrait_Type_Struct_types_tag          1
#define substrait_Type_Struct_type_variation_reference_tag 2
#define substrait_Type_Struct_nullability_tag    3
#define substrait_Type_Time_type_variation_reference_tag 1
#define substrait_Type_Time_nullability_tag      2
#define substrait_Type_Timestamp_type_variation_reference_tag 1
#define substrait_Type_Timestamp_nullability_tag 2
#define substrait_Type_TimestampTZ_type_variation_reference_tag 1
#define substrait_Type_TimestampTZ_nullability_tag 2
#define substrait_Type_UUID_type_variation_reference_tag 1
#define substrait_Type_UUID_nullability_tag      2
#define substrait_Type_VarChar_length_tag        1
#define substrait_Type_VarChar_type_variation_reference_tag 2
#define substrait_Type_VarChar_nullability_tag   3

/* Struct field encoding specification for nanopb */
#define substrait_Type_FIELDLIST(X, a) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (kind,bool_,kind.bool_),   1) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (kind,i8,kind.i8),   2) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (kind,i16,kind.i16),   3) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (kind,i32,kind.i32),   5) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (kind,i64,kind.i64),   7) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (kind,fp32,kind.fp32),  10) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (kind,fp64,kind.fp64),  11) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (kind,string,kind.string),  12) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (kind,binary,kind.binary),  13) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (kind,timestamp,kind.timestamp),  14) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (kind,date,kind.date),  16) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (kind,time,kind.time),  17) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (kind,interval_year,kind.interval_year),  19) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (kind,interval_day,kind.interval_day),  20) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (kind,fixed_char,kind.fixed_char),  21) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (kind,varchar,kind.varchar),  22) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (kind,fixed_binary,kind.fixed_binary),  23) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (kind,decimal,kind.decimal),  24) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (kind,struct_,kind.struct_),  25) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (kind,list,kind.list),  27) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (kind,map,kind.map),  28) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (kind,timestamp_tz,kind.timestamp_tz),  29) \
X(a, CALLBACK, ONEOF,    UINT32,   (kind,user_defined_type_reference,kind.user_defined_type_reference),  31) \
X(a, CALLBACK, ONEOF,    MESSAGE,  (kind,uuid,kind.uuid),  32)
#define substrait_Type_CALLBACK pb_default_field_callback
#define substrait_Type_DEFAULT NULL
#define substrait_Type_kind_bool__MSGTYPE substrait_Type_Boolean
#define substrait_Type_kind_i8_MSGTYPE substrait_Type_I8
#define substrait_Type_kind_i16_MSGTYPE substrait_Type_I16
#define substrait_Type_kind_i32_MSGTYPE substrait_Type_I32
#define substrait_Type_kind_i64_MSGTYPE substrait_Type_I64
#define substrait_Type_kind_fp32_MSGTYPE substrait_Type_FP32
#define substrait_Type_kind_fp64_MSGTYPE substrait_Type_FP64
#define substrait_Type_kind_string_MSGTYPE substrait_Type_String
#define substrait_Type_kind_binary_MSGTYPE substrait_Type_Binary
#define substrait_Type_kind_timestamp_MSGTYPE substrait_Type_Timestamp
#define substrait_Type_kind_date_MSGTYPE substrait_Type_Date
#define substrait_Type_kind_time_MSGTYPE substrait_Type_Time
#define substrait_Type_kind_interval_year_MSGTYPE substrait_Type_IntervalYear
#define substrait_Type_kind_interval_day_MSGTYPE substrait_Type_IntervalDay
#define substrait_Type_kind_fixed_char_MSGTYPE substrait_Type_FixedChar
#define substrait_Type_kind_varchar_MSGTYPE substrait_Type_VarChar
#define substrait_Type_kind_fixed_binary_MSGTYPE substrait_Type_FixedBinary
#define substrait_Type_kind_decimal_MSGTYPE substrait_Type_Decimal
#define substrait_Type_kind_struct__MSGTYPE substrait_Type_Struct
#define substrait_Type_kind_list_MSGTYPE substrait_Type_List
#define substrait_Type_kind_map_MSGTYPE substrait_Type_Map
#define substrait_Type_kind_timestamp_tz_MSGTYPE substrait_Type_TimestampTZ
#define substrait_Type_kind_uuid_MSGTYPE substrait_Type_UUID

#define substrait_Type_Boolean_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       2)
#define substrait_Type_Boolean_CALLBACK pb_default_field_callback
#define substrait_Type_Boolean_DEFAULT NULL

#define substrait_Type_I8_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       2)
#define substrait_Type_I8_CALLBACK pb_default_field_callback
#define substrait_Type_I8_DEFAULT NULL

#define substrait_Type_I16_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       2)
#define substrait_Type_I16_CALLBACK pb_default_field_callback
#define substrait_Type_I16_DEFAULT NULL

#define substrait_Type_I32_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       2)
#define substrait_Type_I32_CALLBACK pb_default_field_callback
#define substrait_Type_I32_DEFAULT NULL

#define substrait_Type_I64_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       2)
#define substrait_Type_I64_CALLBACK pb_default_field_callback
#define substrait_Type_I64_DEFAULT NULL

#define substrait_Type_FP32_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       2)
#define substrait_Type_FP32_CALLBACK pb_default_field_callback
#define substrait_Type_FP32_DEFAULT NULL

#define substrait_Type_FP64_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       2)
#define substrait_Type_FP64_CALLBACK pb_default_field_callback
#define substrait_Type_FP64_DEFAULT NULL

#define substrait_Type_String_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       2)
#define substrait_Type_String_CALLBACK pb_default_field_callback
#define substrait_Type_String_DEFAULT NULL

#define substrait_Type_Binary_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       2)
#define substrait_Type_Binary_CALLBACK pb_default_field_callback
#define substrait_Type_Binary_DEFAULT NULL

#define substrait_Type_Timestamp_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       2)
#define substrait_Type_Timestamp_CALLBACK pb_default_field_callback
#define substrait_Type_Timestamp_DEFAULT NULL

#define substrait_Type_Date_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       2)
#define substrait_Type_Date_CALLBACK pb_default_field_callback
#define substrait_Type_Date_DEFAULT NULL

#define substrait_Type_Time_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       2)
#define substrait_Type_Time_CALLBACK pb_default_field_callback
#define substrait_Type_Time_DEFAULT NULL

#define substrait_Type_TimestampTZ_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       2)
#define substrait_Type_TimestampTZ_CALLBACK pb_default_field_callback
#define substrait_Type_TimestampTZ_DEFAULT NULL

#define substrait_Type_IntervalYear_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       2)
#define substrait_Type_IntervalYear_CALLBACK pb_default_field_callback
#define substrait_Type_IntervalYear_DEFAULT NULL

#define substrait_Type_IntervalDay_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       2)
#define substrait_Type_IntervalDay_CALLBACK pb_default_field_callback
#define substrait_Type_IntervalDay_DEFAULT NULL

#define substrait_Type_UUID_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, UINT32,   type_variation_reference,   1) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       2)
#define substrait_Type_UUID_CALLBACK pb_default_field_callback
#define substrait_Type_UUID_DEFAULT NULL

#define substrait_Type_FixedChar_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, INT32,    length,            1) \
X(a, CALLBACK, SINGULAR, UINT32,   type_variation_reference,   2) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       3)
#define substrait_Type_FixedChar_CALLBACK pb_default_field_callback
#define substrait_Type_FixedChar_DEFAULT NULL

#define substrait_Type_VarChar_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, INT32,    length,            1) \
X(a, CALLBACK, SINGULAR, UINT32,   type_variation_reference,   2) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       3)
#define substrait_Type_VarChar_CALLBACK pb_default_field_callback
#define substrait_Type_VarChar_DEFAULT NULL

#define substrait_Type_FixedBinary_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, INT32,    length,            1) \
X(a, CALLBACK, SINGULAR, UINT32,   type_variation_reference,   2) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       3)
#define substrait_Type_FixedBinary_CALLBACK pb_default_field_callback
#define substrait_Type_FixedBinary_DEFAULT NULL

#define substrait_Type_Decimal_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, INT32,    scale,             1) \
X(a, CALLBACK, SINGULAR, INT32,    precision,         2) \
X(a, CALLBACK, SINGULAR, UINT32,   type_variation_reference,   3) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       4)
#define substrait_Type_Decimal_CALLBACK pb_default_field_callback
#define substrait_Type_Decimal_DEFAULT NULL

#define substrait_Type_Struct_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  types,             1) \
X(a, CALLBACK, SINGULAR, UINT32,   type_variation_reference,   2) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       3)
#define substrait_Type_Struct_CALLBACK pb_default_field_callback
#define substrait_Type_Struct_DEFAULT NULL
#define substrait_Type_Struct_types_MSGTYPE substrait_Type

#define substrait_Type_List_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  type,              1) \
X(a, CALLBACK, SINGULAR, UINT32,   type_variation_reference,   2) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       3)
#define substrait_Type_List_CALLBACK pb_default_field_callback
#define substrait_Type_List_DEFAULT NULL
#define substrait_Type_List_type_MSGTYPE substrait_Type

#define substrait_Type_Map_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  key,               1) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  value,             2) \
X(a, CALLBACK, SINGULAR, UINT32,   type_variation_reference,   3) \
X(a, CALLBACK, SINGULAR, UENUM,    nullability,       4)
#define substrait_Type_Map_CALLBACK pb_default_field_callback
#define substrait_Type_Map_DEFAULT NULL
#define substrait_Type_Map_key_MSGTYPE substrait_Type
#define substrait_Type_Map_value_MSGTYPE substrait_Type

#define substrait_NamedStruct_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   names,             1) \
X(a, CALLBACK, OPTIONAL, MESSAGE,  struct_,           2)
#define substrait_NamedStruct_CALLBACK pb_default_field_callback
#define substrait_NamedStruct_DEFAULT NULL
#define substrait_NamedStruct_struct__MSGTYPE substrait_Type_Struct

extern const pb_msgdesc_t substrait_Type_msg;
extern const pb_msgdesc_t substrait_Type_Boolean_msg;
extern const pb_msgdesc_t substrait_Type_I8_msg;
extern const pb_msgdesc_t substrait_Type_I16_msg;
extern const pb_msgdesc_t substrait_Type_I32_msg;
extern const pb_msgdesc_t substrait_Type_I64_msg;
extern const pb_msgdesc_t substrait_Type_FP32_msg;
extern const pb_msgdesc_t substrait_Type_FP64_msg;
extern const pb_msgdesc_t substrait_Type_String_msg;
extern const pb_msgdesc_t substrait_Type_Binary_msg;
extern const pb_msgdesc_t substrait_Type_Timestamp_msg;
extern const pb_msgdesc_t substrait_Type_Date_msg;
extern const pb_msgdesc_t substrait_Type_Time_msg;
extern const pb_msgdesc_t substrait_Type_TimestampTZ_msg;
extern const pb_msgdesc_t substrait_Type_IntervalYear_msg;
extern const pb_msgdesc_t substrait_Type_IntervalDay_msg;
extern const pb_msgdesc_t substrait_Type_UUID_msg;
extern const pb_msgdesc_t substrait_Type_FixedChar_msg;
extern const pb_msgdesc_t substrait_Type_VarChar_msg;
extern const pb_msgdesc_t substrait_Type_FixedBinary_msg;
extern const pb_msgdesc_t substrait_Type_Decimal_msg;
extern const pb_msgdesc_t substrait_Type_Struct_msg;
extern const pb_msgdesc_t substrait_Type_List_msg;
extern const pb_msgdesc_t substrait_Type_Map_msg;
extern const pb_msgdesc_t substrait_NamedStruct_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define substrait_Type_fields &substrait_Type_msg
#define substrait_Type_Boolean_fields &substrait_Type_Boolean_msg
#define substrait_Type_I8_fields &substrait_Type_I8_msg
#define substrait_Type_I16_fields &substrait_Type_I16_msg
#define substrait_Type_I32_fields &substrait_Type_I32_msg
#define substrait_Type_I64_fields &substrait_Type_I64_msg
#define substrait_Type_FP32_fields &substrait_Type_FP32_msg
#define substrait_Type_FP64_fields &substrait_Type_FP64_msg
#define substrait_Type_String_fields &substrait_Type_String_msg
#define substrait_Type_Binary_fields &substrait_Type_Binary_msg
#define substrait_Type_Timestamp_fields &substrait_Type_Timestamp_msg
#define substrait_Type_Date_fields &substrait_Type_Date_msg
#define substrait_Type_Time_fields &substrait_Type_Time_msg
#define substrait_Type_TimestampTZ_fields &substrait_Type_TimestampTZ_msg
#define substrait_Type_IntervalYear_fields &substrait_Type_IntervalYear_msg
#define substrait_Type_IntervalDay_fields &substrait_Type_IntervalDay_msg
#define substrait_Type_UUID_fields &substrait_Type_UUID_msg
#define substrait_Type_FixedChar_fields &substrait_Type_FixedChar_msg
#define substrait_Type_VarChar_fields &substrait_Type_VarChar_msg
#define substrait_Type_FixedBinary_fields &substrait_Type_FixedBinary_msg
#define substrait_Type_Decimal_fields &substrait_Type_Decimal_msg
#define substrait_Type_Struct_fields &substrait_Type_Struct_msg
#define substrait_Type_List_fields &substrait_Type_List_msg
#define substrait_Type_Map_fields &substrait_Type_Map_msg
#define substrait_NamedStruct_fields &substrait_NamedStruct_msg

/* Maximum encoded size of messages (where known) */
/* substrait_Type_size depends on runtime parameters */
/* substrait_Type_Boolean_size depends on runtime parameters */
/* substrait_Type_I8_size depends on runtime parameters */
/* substrait_Type_I16_size depends on runtime parameters */
/* substrait_Type_I32_size depends on runtime parameters */
/* substrait_Type_I64_size depends on runtime parameters */
/* substrait_Type_FP32_size depends on runtime parameters */
/* substrait_Type_FP64_size depends on runtime parameters */
/* substrait_Type_String_size depends on runtime parameters */
/* substrait_Type_Binary_size depends on runtime parameters */
/* substrait_Type_Timestamp_size depends on runtime parameters */
/* substrait_Type_Date_size depends on runtime parameters */
/* substrait_Type_Time_size depends on runtime parameters */
/* substrait_Type_TimestampTZ_size depends on runtime parameters */
/* substrait_Type_IntervalYear_size depends on runtime parameters */
/* substrait_Type_IntervalDay_size depends on runtime parameters */
/* substrait_Type_UUID_size depends on runtime parameters */
/* substrait_Type_FixedChar_size depends on runtime parameters */
/* substrait_Type_VarChar_size depends on runtime parameters */
/* substrait_Type_FixedBinary_size depends on runtime parameters */
/* substrait_Type_Decimal_size depends on runtime parameters */
/* substrait_Type_Struct_size depends on runtime parameters */
/* substrait_Type_List_size depends on runtime parameters */
/* substrait_Type_Map_size depends on runtime parameters */
/* substrait_NamedStruct_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
