/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "substrait/algebra.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(substrait_RelCommon, substrait_RelCommon, AUTO)


PB_BIND(substrait_RelCommon_Direct, substrait_RelCommon_Direct, AUTO)


PB_BIND(substrait_RelCommon_Emit, substrait_RelCommon_Emit, AUTO)


PB_BIND(substrait_RelCommon_Hint, substrait_RelCommon_Hint, AUTO)


PB_BIND(substrait_RelCommon_Hint_Stats, substrait_RelCommon_Hint_Stats, AUTO)


PB_BIND(substrait_RelCommon_Hint_RuntimeConstraint, substrait_RelCommon_Hint_RuntimeConstraint, AUTO)


PB_BIND(substrait_ReadRel, substrait_ReadRel, AUTO)


PB_BIND(substrait_ReadRel_NamedTable, substrait_ReadRel_NamedTable, AUTO)


PB_BIND(substrait_ReadRel_VirtualTable, substrait_ReadRel_VirtualTable, AUTO)


PB_BIND(substrait_ReadRel_ExtensionTable, substrait_ReadRel_ExtensionTable, AUTO)


PB_BIND(substrait_ReadRel_LocalFiles, substrait_ReadRel_LocalFiles, AUTO)


PB_BIND(substrait_ReadRel_LocalFiles_FileOrFiles, substrait_ReadRel_LocalFiles_FileOrFiles, AUTO)


PB_BIND(substrait_ReadRel_LocalFiles_FileOrFiles_ParquetReadOptions, substrait_ReadRel_LocalFiles_FileOrFiles_ParquetReadOptions, AUTO)


PB_BIND(substrait_ReadRel_LocalFiles_FileOrFiles_ArrowReadOptions, substrait_ReadRel_LocalFiles_FileOrFiles_ArrowReadOptions, AUTO)


PB_BIND(substrait_ReadRel_LocalFiles_FileOrFiles_OrcReadOptions, substrait_ReadRel_LocalFiles_FileOrFiles_OrcReadOptions, AUTO)


PB_BIND(substrait_ReadRel_LocalFiles_FileOrFiles_DwrfReadOptions, substrait_ReadRel_LocalFiles_FileOrFiles_DwrfReadOptions, AUTO)


PB_BIND(substrait_ProjectRel, substrait_ProjectRel, AUTO)


PB_BIND(substrait_JoinRel, substrait_JoinRel, AUTO)


PB_BIND(substrait_CrossRel, substrait_CrossRel, AUTO)


PB_BIND(substrait_FetchRel, substrait_FetchRel, AUTO)


PB_BIND(substrait_AggregateRel, substrait_AggregateRel, AUTO)


PB_BIND(substrait_AggregateRel_Grouping, substrait_AggregateRel_Grouping, AUTO)


PB_BIND(substrait_AggregateRel_Measure, substrait_AggregateRel_Measure, AUTO)


PB_BIND(substrait_SortRel, substrait_SortRel, AUTO)


PB_BIND(substrait_FilterRel, substrait_FilterRel, AUTO)


PB_BIND(substrait_SetRel, substrait_SetRel, AUTO)


PB_BIND(substrait_ExtensionSingleRel, substrait_ExtensionSingleRel, AUTO)


PB_BIND(substrait_ExtensionLeafRel, substrait_ExtensionLeafRel, AUTO)


PB_BIND(substrait_ExtensionMultiRel, substrait_ExtensionMultiRel, AUTO)


PB_BIND(substrait_ExchangeRel, substrait_ExchangeRel, AUTO)


PB_BIND(substrait_ExchangeRel_ScatterFields, substrait_ExchangeRel_ScatterFields, AUTO)


PB_BIND(substrait_ExchangeRel_SingleBucketExpression, substrait_ExchangeRel_SingleBucketExpression, AUTO)


PB_BIND(substrait_ExchangeRel_MultiBucketExpression, substrait_ExchangeRel_MultiBucketExpression, AUTO)


PB_BIND(substrait_ExchangeRel_Broadcast, substrait_ExchangeRel_Broadcast, AUTO)


PB_BIND(substrait_ExchangeRel_RoundRobin, substrait_ExchangeRel_RoundRobin, AUTO)


PB_BIND(substrait_ExchangeRel_ExchangeTarget, substrait_ExchangeRel_ExchangeTarget, AUTO)


PB_BIND(substrait_RelRoot, substrait_RelRoot, AUTO)


PB_BIND(substrait_Rel, substrait_Rel, AUTO)


PB_BIND(substrait_NamedObjectWrite, substrait_NamedObjectWrite, AUTO)


PB_BIND(substrait_ExtensionObject, substrait_ExtensionObject, AUTO)


PB_BIND(substrait_DdlRel, substrait_DdlRel, AUTO)


PB_BIND(substrait_WriteRel, substrait_WriteRel, AUTO)


PB_BIND(substrait_FunctionArgument, substrait_FunctionArgument, AUTO)


PB_BIND(substrait_FunctionOption, substrait_FunctionOption, AUTO)


PB_BIND(substrait_Expression, substrait_Expression, AUTO)


PB_BIND(substrait_Expression_Enum, substrait_Expression_Enum, AUTO)


PB_BIND(substrait_Expression_Enum_Empty, substrait_Expression_Enum_Empty, AUTO)


PB_BIND(substrait_Expression_Literal, substrait_Expression_Literal, AUTO)


PB_BIND(substrait_Expression_Literal_VarChar, substrait_Expression_Literal_VarChar, AUTO)


PB_BIND(substrait_Expression_Literal_Decimal, substrait_Expression_Literal_Decimal, AUTO)


PB_BIND(substrait_Expression_Literal_Map, substrait_Expression_Literal_Map, AUTO)


PB_BIND(substrait_Expression_Literal_Map_KeyValue, substrait_Expression_Literal_Map_KeyValue, AUTO)


PB_BIND(substrait_Expression_Literal_IntervalYearToMonth, substrait_Expression_Literal_IntervalYearToMonth, AUTO)


PB_BIND(substrait_Expression_Literal_IntervalDayToSecond, substrait_Expression_Literal_IntervalDayToSecond, AUTO)


PB_BIND(substrait_Expression_Literal_Struct, substrait_Expression_Literal_Struct, AUTO)


PB_BIND(substrait_Expression_Literal_List, substrait_Expression_Literal_List, AUTO)


PB_BIND(substrait_Expression_Literal_UserDefined, substrait_Expression_Literal_UserDefined, AUTO)


PB_BIND(substrait_Expression_ScalarFunction, substrait_Expression_ScalarFunction, AUTO)


PB_BIND(substrait_Expression_WindowFunction, substrait_Expression_WindowFunction, AUTO)


PB_BIND(substrait_Expression_WindowFunction_Bound, substrait_Expression_WindowFunction_Bound, AUTO)


PB_BIND(substrait_Expression_WindowFunction_Bound_Preceding, substrait_Expression_WindowFunction_Bound_Preceding, AUTO)


PB_BIND(substrait_Expression_WindowFunction_Bound_Following, substrait_Expression_WindowFunction_Bound_Following, AUTO)


PB_BIND(substrait_Expression_WindowFunction_Bound_CurrentRow, substrait_Expression_WindowFunction_Bound_CurrentRow, AUTO)


PB_BIND(substrait_Expression_WindowFunction_Bound_Unbounded, substrait_Expression_WindowFunction_Bound_Unbounded, AUTO)


PB_BIND(substrait_Expression_IfThen, substrait_Expression_IfThen, AUTO)


PB_BIND(substrait_Expression_IfThen_IfClause, substrait_Expression_IfThen_IfClause, AUTO)


PB_BIND(substrait_Expression_Cast, substrait_Expression_Cast, AUTO)


PB_BIND(substrait_Expression_SwitchExpression, substrait_Expression_SwitchExpression, AUTO)


PB_BIND(substrait_Expression_SwitchExpression_IfValue, substrait_Expression_SwitchExpression_IfValue, AUTO)


PB_BIND(substrait_Expression_SingularOrList, substrait_Expression_SingularOrList, AUTO)


PB_BIND(substrait_Expression_MultiOrList, substrait_Expression_MultiOrList, AUTO)


PB_BIND(substrait_Expression_MultiOrList_Record, substrait_Expression_MultiOrList_Record, AUTO)


PB_BIND(substrait_Expression_EmbeddedFunction, substrait_Expression_EmbeddedFunction, AUTO)


PB_BIND(substrait_Expression_EmbeddedFunction_PythonPickleFunction, substrait_Expression_EmbeddedFunction_PythonPickleFunction, AUTO)


PB_BIND(substrait_Expression_EmbeddedFunction_WebAssemblyFunction, substrait_Expression_EmbeddedFunction_WebAssemblyFunction, AUTO)


PB_BIND(substrait_Expression_ReferenceSegment, substrait_Expression_ReferenceSegment, AUTO)


PB_BIND(substrait_Expression_ReferenceSegment_MapKey, substrait_Expression_ReferenceSegment_MapKey, AUTO)


PB_BIND(substrait_Expression_ReferenceSegment_StructField, substrait_Expression_ReferenceSegment_StructField, AUTO)


PB_BIND(substrait_Expression_ReferenceSegment_ListElement, substrait_Expression_ReferenceSegment_ListElement, AUTO)


PB_BIND(substrait_Expression_MaskExpression, substrait_Expression_MaskExpression, AUTO)


PB_BIND(substrait_Expression_MaskExpression_Select, substrait_Expression_MaskExpression_Select, AUTO)


PB_BIND(substrait_Expression_MaskExpression_StructSelect, substrait_Expression_MaskExpression_StructSelect, AUTO)


PB_BIND(substrait_Expression_MaskExpression_StructItem, substrait_Expression_MaskExpression_StructItem, AUTO)


PB_BIND(substrait_Expression_MaskExpression_ListSelect, substrait_Expression_MaskExpression_ListSelect, AUTO)


PB_BIND(substrait_Expression_MaskExpression_ListSelect_ListSelectItem, substrait_Expression_MaskExpression_ListSelect_ListSelectItem, AUTO)


PB_BIND(substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListElement, substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListElement, AUTO)


PB_BIND(substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListSlice, substrait_Expression_MaskExpression_ListSelect_ListSelectItem_ListSlice, AUTO)


PB_BIND(substrait_Expression_MaskExpression_MapSelect, substrait_Expression_MaskExpression_MapSelect, AUTO)


PB_BIND(substrait_Expression_MaskExpression_MapSelect_MapKey, substrait_Expression_MaskExpression_MapSelect_MapKey, AUTO)


PB_BIND(substrait_Expression_MaskExpression_MapSelect_MapKeyExpression, substrait_Expression_MaskExpression_MapSelect_MapKeyExpression, AUTO)


PB_BIND(substrait_Expression_FieldReference, substrait_Expression_FieldReference, AUTO)


PB_BIND(substrait_Expression_FieldReference_RootReference, substrait_Expression_FieldReference_RootReference, AUTO)


PB_BIND(substrait_Expression_FieldReference_OuterReference, substrait_Expression_FieldReference_OuterReference, AUTO)


PB_BIND(substrait_Expression_Subquery, substrait_Expression_Subquery, AUTO)


PB_BIND(substrait_Expression_Subquery_Scalar, substrait_Expression_Subquery_Scalar, AUTO)


PB_BIND(substrait_Expression_Subquery_InPredicate, substrait_Expression_Subquery_InPredicate, AUTO)


PB_BIND(substrait_Expression_Subquery_SetPredicate, substrait_Expression_Subquery_SetPredicate, AUTO)


PB_BIND(substrait_Expression_Subquery_SetComparison, substrait_Expression_Subquery_SetComparison, AUTO)


PB_BIND(substrait_SortField, substrait_SortField, AUTO)


PB_BIND(substrait_AggregateFunction, substrait_AggregateFunction, AUTO)


PB_BIND(substrait_AggregateFunction_ReferenceRel, substrait_AggregateFunction_ReferenceRel, AUTO)
















#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

