/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "substrait/any.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(substrait_Any, substrait_Any, AUTO)


PB_BIND(substrait_Empty, substrait_Empty, AUTO)



