/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "substrait/extensions/extensions.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(substrait_extensions_SimpleExtensionURI, substrait_extensions_SimpleExtensionURI, AUTO)


PB_BIND(substrait_extensions_SimpleExtensionDeclaration, substrait_extensions_SimpleExtensionDeclaration, AUTO)


PB_BIND(substrait_extensions_SimpleExtensionDeclaration_ExtensionType, substrait_extensions_SimpleExtensionDeclaration_ExtensionType, AUTO)


PB_BIND(substrait_extensions_SimpleExtensionDeclaration_ExtensionTypeVariation, substrait_extensions_SimpleExtensionDeclaration_ExtensionTypeVariation, AUTO)


PB_BIND(substrait_extensions_SimpleExtensionDeclaration_ExtensionFunction, substrait_extensions_SimpleExtensionDeclaration_ExtensionFunction, AUTO)


PB_BIND(substrait_extensions_AdvancedExtension, substrait_extensions_AdvancedExtension, AUTO)



