/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "substrait/function.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(substrait_FunctionSignature, substrait_FunctionSignature, AUTO)


PB_BIND(substrait_FunctionSignature_FinalArgVariadic, substrait_FunctionSignature_FinalArgVariadic, AUTO)


PB_BIND(substrait_FunctionSignature_FinalArgNormal, substrait_FunctionSignature_FinalArgNormal, AUTO)


PB_BIND(substrait_FunctionSignature_Scalar, substrait_FunctionSignature_Scalar, AUTO)


PB_BIND(substrait_FunctionSignature_Aggregate, substrait_FunctionSignature_Aggregate, AUTO)


PB_BIND(substrait_FunctionSignature_Window, substrait_FunctionSignature_Window, AUTO)


PB_BIND(substrait_FunctionSignature_Description, substrait_FunctionSignature_Description, AUTO)


PB_BIND(substrait_FunctionSignature_Implementation, substrait_FunctionSignature_Implementation, AUTO)


PB_BIND(substrait_FunctionSignature_Argument, substrait_FunctionSignature_Argument, AUTO)


PB_BIND(substrait_FunctionSignature_Argument_ValueArgument, substrait_FunctionSignature_Argument_ValueArgument, AUTO)


PB_BIND(substrait_FunctionSignature_Argument_TypeArgument, substrait_FunctionSignature_Argument_TypeArgument, AUTO)


PB_BIND(substrait_FunctionSignature_Argument_EnumArgument, substrait_FunctionSignature_Argument_EnumArgument, AUTO)






