/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "substrait/parameterized_types.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(substrait_ParameterizedType, substrait_ParameterizedType, AUTO)


PB_BIND(substrait_ParameterizedType_TypeParameter, substrait_ParameterizedType_TypeParameter, AUTO)


PB_BIND(substrait_ParameterizedType_IntegerParameter, substrait_ParameterizedType_IntegerParameter, AUTO)


PB_BIND(substrait_ParameterizedType_NullableInteger, substrait_ParameterizedType_NullableInteger, AUTO)


PB_BIND(substrait_ParameterizedType_ParameterizedFixedChar, substrait_ParameterizedType_ParameterizedFixedChar, AUTO)


PB_BIND(substrait_ParameterizedType_ParameterizedVarChar, substrait_ParameterizedType_ParameterizedVarChar, AUTO)


PB_BIND(substrait_ParameterizedType_ParameterizedFixedBinary, substrait_ParameterizedType_ParameterizedFixedBinary, AUTO)


PB_BIND(substrait_ParameterizedType_ParameterizedDecimal, substrait_ParameterizedType_ParameterizedDecimal, AUTO)


PB_BIND(substrait_ParameterizedType_ParameterizedStruct, substrait_ParameterizedType_ParameterizedStruct, AUTO)


PB_BIND(substrait_ParameterizedType_ParameterizedNamedStruct, substrait_ParameterizedType_ParameterizedNamedStruct, AUTO)


PB_BIND(substrait_ParameterizedType_ParameterizedList, substrait_ParameterizedType_ParameterizedList, AUTO)


PB_BIND(substrait_ParameterizedType_ParameterizedMap, substrait_ParameterizedType_ParameterizedMap, AUTO)


PB_BIND(substrait_ParameterizedType_IntegerOption, substrait_ParameterizedType_IntegerOption, AUTO)



