/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "substrait/plan.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(substrait_PlanRel, substrait_PlanRel, AUTO)


PB_BIND(substrait_Plan, substrait_Plan, AUTO)



