/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "substrait/relations.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(substrait_RelCommon, substrait_RelCommon, AUTO)


PB_BIND(substrait_RelCommon_Direct, substrait_RelCommon_Direct, AUTO)


PB_BIND(substrait_RelCommon_Emit, substrait_RelCommon_Emit, AUTO)


PB_BIND(substrait_RelCommon_Hint, substrait_RelCommon_Hint, AUTO)


PB_BIND(substrait_RelCommon_Hint_Stats, substrait_RelCommon_Hint_Stats, AUTO)


PB_BIND(substrait_RelCommon_Hint_RuntimeConstraint, substrait_RelCommon_Hint_RuntimeConstraint, AUTO)


PB_BIND(substrait_ReadRel, substrait_ReadRel, AUTO)


PB_BIND(substrait_ReadRel_NamedTable, substrait_ReadRel_NamedTable, AUTO)


PB_BIND(substrait_ReadRel_VirtualTable, substrait_ReadRel_VirtualTable, AUTO)


PB_BIND(substrait_ReadRel_ExtensionTable, substrait_ReadRel_ExtensionTable, AUTO)


PB_BIND(substrait_ReadRel_LocalFiles, substrait_ReadRel_LocalFiles, AUTO)


PB_BIND(substrait_ReadRel_LocalFiles_FileOrFiles, substrait_ReadRel_LocalFiles_FileOrFiles, AUTO)


PB_BIND(substrait_ProjectRel, substrait_ProjectRel, AUTO)


PB_BIND(substrait_JoinRel, substrait_JoinRel, AUTO)


PB_BIND(substrait_FetchRel, substrait_FetchRel, AUTO)


PB_BIND(substrait_AggregateRel, substrait_AggregateRel, AUTO)


PB_BIND(substrait_AggregateRel_Grouping, substrait_AggregateRel_Grouping, AUTO)


PB_BIND(substrait_AggregateRel_Measure, substrait_AggregateRel_Measure, AUTO)


PB_BIND(substrait_SortRel, substrait_SortRel, AUTO)


PB_BIND(substrait_FilterRel, substrait_FilterRel, AUTO)


PB_BIND(substrait_SetRel, substrait_SetRel, AUTO)


PB_BIND(substrait_ExtensionSingleRel, substrait_ExtensionSingleRel, AUTO)


PB_BIND(substrait_ExtensionLeafRel, substrait_ExtensionLeafRel, AUTO)


PB_BIND(substrait_ExtensionMultiRel, substrait_ExtensionMultiRel, AUTO)


PB_BIND(substrait_RelRoot, substrait_RelRoot, AUTO)


PB_BIND(substrait_Rel, substrait_Rel, AUTO)






#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

