/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "substrait/type.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(substrait_Type, substrait_Type, AUTO)


PB_BIND(substrait_Type_Boolean, substrait_Type_Boolean, AUTO)


PB_BIND(substrait_Type_I8, substrait_Type_I8, AUTO)


PB_BIND(substrait_Type_I16, substrait_Type_I16, AUTO)


PB_BIND(substrait_Type_I32, substrait_Type_I32, AUTO)


PB_BIND(substrait_Type_I64, substrait_Type_I64, AUTO)


PB_BIND(substrait_Type_FP32, substrait_Type_FP32, AUTO)


PB_BIND(substrait_Type_FP64, substrait_Type_FP64, AUTO)


PB_BIND(substrait_Type_String, substrait_Type_String, AUTO)


PB_BIND(substrait_Type_Binary, substrait_Type_Binary, AUTO)


PB_BIND(substrait_Type_Timestamp, substrait_Type_Timestamp, AUTO)


PB_BIND(substrait_Type_Date, substrait_Type_Date, AUTO)


PB_BIND(substrait_Type_Time, substrait_Type_Time, AUTO)


PB_BIND(substrait_Type_TimestampTZ, substrait_Type_TimestampTZ, AUTO)


PB_BIND(substrait_Type_IntervalYear, substrait_Type_IntervalYear, AUTO)


PB_BIND(substrait_Type_IntervalDay, substrait_Type_IntervalDay, AUTO)


PB_BIND(substrait_Type_UUID, substrait_Type_UUID, AUTO)


PB_BIND(substrait_Type_FixedChar, substrait_Type_FixedChar, AUTO)


PB_BIND(substrait_Type_VarChar, substrait_Type_VarChar, AUTO)


PB_BIND(substrait_Type_FixedBinary, substrait_Type_FixedBinary, AUTO)


PB_BIND(substrait_Type_Decimal, substrait_Type_Decimal, AUTO)


PB_BIND(substrait_Type_Struct, substrait_Type_Struct, AUTO)


PB_BIND(substrait_Type_List, substrait_Type_List, AUTO)


PB_BIND(substrait_Type_Map, substrait_Type_Map, AUTO)


PB_BIND(substrait_Type_UserDefined, substrait_Type_UserDefined, AUTO)


PB_BIND(substrait_Type_Parameter, substrait_Type_Parameter, AUTO)


PB_BIND(substrait_NamedStruct, substrait_NamedStruct, AUTO)




