/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "substrait/type_expressions.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(substrait_DerivationExpression, substrait_DerivationExpression, AUTO)


PB_BIND(substrait_DerivationExpression_ExpressionFixedChar, substrait_DerivationExpression_ExpressionFixedChar, AUTO)


PB_BIND(substrait_DerivationExpression_ExpressionVarChar, substrait_DerivationExpression_ExpressionVarChar, AUTO)


PB_BIND(substrait_DerivationExpression_ExpressionFixedBinary, substrait_DerivationExpression_ExpressionFixedBinary, AUTO)


PB_BIND(substrait_DerivationExpression_ExpressionDecimal, substrait_DerivationExpression_ExpressionDecimal, AUTO)


PB_BIND(substrait_DerivationExpression_ExpressionStruct, substrait_DerivationExpression_ExpressionStruct, AUTO)


PB_BIND(substrait_DerivationExpression_ExpressionNamedStruct, substrait_DerivationExpression_ExpressionNamedStruct, AUTO)


PB_BIND(substrait_DerivationExpression_ExpressionList, substrait_DerivationExpression_ExpressionList, AUTO)


PB_BIND(substrait_DerivationExpression_ExpressionMap, substrait_DerivationExpression_ExpressionMap, AUTO)


PB_BIND(substrait_DerivationExpression_IfElse, substrait_DerivationExpression_IfElse, AUTO)


PB_BIND(substrait_DerivationExpression_UnaryOp, substrait_DerivationExpression_UnaryOp, AUTO)


PB_BIND(substrait_DerivationExpression_BinaryOp, substrait_DerivationExpression_BinaryOp, AUTO)


PB_BIND(substrait_DerivationExpression_ReturnProgram, substrait_DerivationExpression_ReturnProgram, AUTO)


PB_BIND(substrait_DerivationExpression_ReturnProgram_Assignment, substrait_DerivationExpression_ReturnProgram_Assignment, AUTO)





