# Generated by cpp11: do not edit by hand

r_encode_substrait_Type_Boolean <- function(type_variation_reference, nullablity) {
  .Call(`_substrait_r_encode_substrait_Type_Boolean`, type_variation_reference, nullablity)
}
